### ISSUE TITLE
Help with finding a model - iSyp821

### ISSUE THREAD

**Issue by abshah1** [opencobra/cobrapy#1062]
### Checklist

- [x] I searched the [documentation](https://cobrapy.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [x] I looked up "How to do ... in cobrapy" on a search engine.

### Question

Hi, I am building a metabolic map using Cyannobacteria 11901  as the organism. I looking for a model, specifically iSyp821.json but i cannot find it anywhere, if anyone can help it would be greatly appreciated.

**Comment by Midnighter** [comment]
I see the model you refer to described in an Excel sheet here https://ars.els-cdn.com/content/image/1-s2.0-S0005272816306909-mmc1.xlsx so that would require some work in parsing the information to a metabolic model.

This is not really a cobrapy related question, maybe you can contact the authors to ask for a JSON or SBML version?
