### ISSUE TITLE
iMAT+MTA functions on Python

### ISSUE THREAD

**Issue by RolandLendsley** [opencobra/cobrapy#1132]
is the iMAT (https://github.com/opencobra/cobratoolbox/blob/6c1ba69dfd7adbf121a3b987a3446b3d7fdc15ed/src/dataIntegration/transcriptomics/iMAT/iMAT.m) and MTA algorithm from cobratoolbox(matlab) available on cobrapy too?

If not, would you think about implementing it soon on cobrapy?
If that's not the case, could you provide a swift alternative to run iMAT/MAT within a Python based project?

Thank you,
Roland

**Comment by cdiener** [comment]
Most of the metabolic reconstruction algorithms were slated to be added to [driven](https://github.com/opencobra/driven). However, that has been stalled since nobody wanted to pick this up. There is an implementation of iMAT [in there](https://github.com/opencobra/driven/blob/c0f7f5e391362bd87cbc001b6fadf5960c9a655b/driven/flux_analysis/transcriptomics.py#L103) but I would not bet that it still works (last updated several years ago). There are sone actively maintained alternatives on https://opencobra.github.io/cobrapy/tags/reconstruction/ you could check out.
