### ISSUE TITLE
Remove and change genes from model

### ISSUE THREAD

**Issue by paocorbin** [opencobra/cobrapy#1157]
### Checklist
- [ x]  I searched the [documentation](https://cobrapy.readthedocs.io).
- [ x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ x] I looked up "How to do ... in cobrapy" on a search engine.

### Genes not removed from model if they are not involved in any reaction

Hello,
I am changing all the GPRs of my model because I have re-annotated the genome. And I have noticed that the old gene objects are in the model, although there is non-reactions associated. 
I thought that when you changed all the GPRs associated with one gene, the gene object was removed, but is not happening. 

Here is an example for the textbook model and for one gene (b1773):

```py
import cobra.test

cobra_model = cobra.test.create_test_model("textbook")

old_gpr = cobra_model.reactions.FBA.gene_reaction_rule
new_gpr = old_gpr.replace('b1773', 'b2334')
cobra_model.reactions.FBA.gene_reaction_rule = new_gpr
```

```py
display(cobra_model.genes.b1773)
display(cobra_model.genes.b2334)
```
The new gene b2334 appears in the reaction FBA, and the old gene b1773 is in the model with 0 reactions associated.

Also, when you try to remove all genes with 0 reactions associated, using the ' .remove_from_model() ' function, it is imposible to delete all in once. I do not know if it is a problem of the model or of my code, but I need to execute this code more than once in order to delete all the "orphan" genes:

```py
for g in cobra_model.genes:
    if len(g.reactions) == 0:
        cobra_model.genes.get_by_id(g.id).remove_from_model()
```

Any ideas?
Thank you.

**Comment by paocorbin** [comment]
Sorry, the output of :

```
python -c "import cobra;print(cobra.show_versions())"
```

System Information
==================
OS                     Linux
OS-release 5.13.0-30-generic
Python                 3.8.5


Package Versions
================
appdirs                                            1.4.4
black ; extra == 'development'             not installed
bumpversion ; extra == 'development'       not installed
cobra                                             0.22.1
depinfo                                            1.7.0
diskcache                                          5.2.1
future                                            0.18.2
httpx                                             0.21.1
importlib-resources                                5.4.0
isort                                              5.6.4
numpy                                             1.20.1
optlang                                            1.5.2
pandas                                             1.3.4
pip                                               21.1.1
pydantic                                           1.8.2
python-libsbml                                    5.19.0
rich                                             10.14.0
ruamel.yaml                                      0.17.17
scipy                                              1.5.2
setuptools                           50.3.1.post20201107
swiglpk                                            5.0.3
tox ; extra == 'development'               not installed
wheel                                             0.35.1
None

**Comment by cdiener** [comment]
Sorry can you update your cobrapy to 0.23.0? The issue may still exist there but the GPRs were recently revamped so we should check.

**Comment by Midnighter** [comment]
*0.24.0 (due to safety release pipeline failed but I manually uploaded the package to PyPI)

**Comment by paocorbin** [comment]
I update cobrapy to 0.24.0 and I have the same problems.

**Comment by Midnighter** [comment]
Yeah, I can see why it is happening. Basically, we would need to remember previous genes and then remove the difference with the new genes from the model `old_genes - new_genes` if they are not needed elsewhere. However, is this always the desired behavior? When removing reactions, there is an option whether or not to remove metabolites that become orphaned.

@akaviaLab any thoughts from your side since you recently worked on this part?

**Comment by akaviaLab** [comment]
Okay. I think there are two questions
1) Should genes that are not used be removed from the model? 
I'm not sure if that should happen - you guys need to decide yes/no.
I could modify _update_genes_from_gpr to remove unused genes, since _update_genes_from_gpr() is run every time the gene_reaction_rule is changed. If that's what we want, I'll add something so when the reaction.gpr is changed, it will also delete genes from the model.

2)Gene. remove_from_model() is an old function, with deprecation warning. It uses weird code that was hard for me to update with the GPR class.
It looks like this is one of the cases that it doesn't work well.
I would strongly prefer replacing the internal code with cobra.manipulation.remove_genes, as the warning states. Instead of trying to fix the old code. Then it should work properly, since I tested cobra.manipulation.remove_genes with the GPR class.

**Comment by akaviaLab** [comment]
One more comment. I looked at the code before I did my changes 0bbad14ee36406ea14c06f44e9cdd216182b945a
and I don't think that removing the genes from all GPRs has lead them to be removed.

On the other hand, renaming genes via cobra.manipulation.modify.rename_genes will remove genes that are no longer used. Obviously cobra.manipulation.delete.remove_genes() removes the genes (and by default, removes reactions using them).

This seems like the behavior is different between cobra.manipulation.modify.rename_genes and reaction.gene_reaction_rule()

@Midnighter - do you think that in this case, we should modify the code so that renaming via modifying the gene_reaction_rule() removes unused genes?
Should the renamer keep unused genes instead?

Also, I will reiterate my desire to get rid of the cobra.core.gene.remove_from_model() and just replace the code with a call to cobra.manipulation.delete.remove_genes()

**Comment by akaviaLab** [comment]
@parcobin - for now, you can use cobra.manipulation.modify.rename_genes() to rename all the genes, which will remove unused genes from the model if that's what you like.

**Comment by paocorbin** [comment]
Okay, thank you for your responses. I will use cobra.manipulation.modify.rename_genes() instead because I do not need the orphan genes.

**Comment by Midnighter** [comment]
My thoughts were going a bit back and forth on this since removing genes can be quite destructive. A gene holds annotations and other information that you cannot simply re-add by changing the `gene_reaction_rule` string to its previous version. However, I now agree that it's basically a shortcut function and should thus remove genes. If one wants finer grained control, there are other functions for that.

**Comment by Midnighter** [comment]
> Also, I will reiterate my desire to get rid of the cobra.core.gene.remove_from_model() and just replace the code with a call to cobra.manipulation.delete.remove_genes()

Agree 👍🏼
