### ISSUE TITLE
json-schema for json export

### ISSUE THREAD

**Issue by zakandrewking** [opencobra/cobrapy#125]
To ensure the long-term viability of exported JSON models, it would be good to define a schema for them. [json-schema](http://json-schema.org/) lets you define these easily, and validators are available in a number of languages, including Python and JavaScript.

[Escher](https://zakandrewking.github.io/escher/) will use json-schema for defining the Escher map file format. We can also consider *.escher* and *.cobra* filename extensions to clarify which file is which.

I can help out with this.

**Comment by phantomas1234** [comment]
Ok, regarding #170, why would you have an annotation attribute for metabolites and not for reactions? SBML would also be ok but much harder to implement I guess. I generated a couple of universal models from metanetx and using cobrapy's reaction.annotation was pretty useful in that respect. Is there any specific reason to not include this in the JSON spec?

**Comment by aebrahim** [comment]
There isn't really a good reason not to include it in the JSON spec, other than "laziness." If it makes your life easier, we can include this in the JSON format (from the cobrapy perspective, not sure about the escher perpsective).

I brought up SBML for storage of these efforts for a kind of different reason: in my quest to make cobrapy more "maintainable", I wanted to focus on specific use cases for each of the supported I/O formats to avoid duplication of effort and features:

SBML - general purpose storage of models
JSON - working with escher
mat - working with cobra toolbox (until it supports SBML3+fbc2)
pickle - specific cobrapy-only use cases

If we go with this, it would make sense for SBML to be the places where features like this get supported. While working with SBML files and all their various flavors is often a pain (and getting support for features we need will probably take way too much time and effort), the unfortunate fact is that it is the standard for modeling, and cobra should probably "play ball" and use it.

I'd like to know your general thoughts on this, @zakandrewking and @phantomas1234 

@phantomas1234 What are your use cases for reaction.annotation? Was it something like ```reaction.annotation["metanetx_id"] = 10343```? Adding support for something like that to SBML shouldn't be too hard (and something I was planning on implementing anyways), but for arbitrary expressions you are right that SBML support will be much harder.

**Comment by phantomas1234** [comment]
Laziness doesn't really count though because I served you the PR on a golden platter :smiley: 

@aebrahim I guess I was not aware that the JSON schema was primarily intended for escher (given that bigg.ucsd.edu currently doesn't serve SBML via the API I thought the JSON models would be a good way to serialize models). In principle I agree that SBML should be the standard for storing models (if they can be read fast enough). pickles are just too large and too slow to read. I found the JSON files to be very convenient for non-sharing serialization. Anyways, I just hacked my way around it by adding annotation myself to `_to_dict(model)` for the few models I wanted to store. I will try writing them to SBML+FBC and test your parsers. Doesn't really solve the problem with the annotations though ... I don't think it would be too hard to translate the dict content of `reaction.annotation` into some _well formatted xml_ that can be placed into the SBML annotation tags (see screenshot). Andreas D. would be a good person to ask for how to proceed. 
![image](https://cloud.githubusercontent.com/assets/55217/8809416/de31fd34-2fe8-11e5-8770-04277c55c52e.png)

**Comment by aebrahim** [comment]
Yeah I'm just that lazy :) In all seriousness though, Zak and I have talked about updating the JSON format anyways, and I'd like to do them at the same time (so the format only has to change once), so this wouldn't get merged until that is finalized.

SBML I/O is now a lot faster than it used to be with libsbml (by a factor of 2-3x for large models like iJO1366).

And yes, I definitely intend to consult Andreas on how to do this for SBML. Can you send me an example of the type of annotation you have with your models?

**Comment by aebrahim** [comment]
Also, I don't think the new bigg serves JSON models via the api. They're treated just like the SBML models (static exported files).

**Comment by zakandrewking** [comment]
Some comments:

- JSON will be useful for Escher, and also any other web applications that rely on Escher or BiGG. JSON is going to be far easier to work with on the web.
- BiGG does serve JSON right now in the api (e.g. http://bigg.ucsd.edu/api/v2/models/iJO1366/download)
- Users will expect that the JSON format includes the content from all attributes for reaction, metabolite, and gene objects in the COBRApy model. If we ignore any of these attributes, people (a.k.a. me) will get confused. Are there any attributes we currently ignore in the export?

**Comment by aebrahim** [comment]
OK. So looks like this should definitely get merged.
