### ISSUE TITLE
Decouple Gene from Species

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobrapy#145]
A gene does not have a formula or charge. Still need to determine if Species should be deprecated, as there are some common functions between Gene and Metabolite with respect to reaction association.

This will also require less memory.

**Comment by afif-elghraoui** [comment]
I would vote to keep the Species class. I've written a bunch of code for ME-model support and want to work it in to cobrapy (it needs to be reformulated a bit because it's not written as part of cobrapy currently). The way I plan the integration uses Species as a main class. I would subclass from there Macromolecules and so forth.

Anyway, I want to get your feedback on the design of it before making the reformulation and sending a pull request. I was going to ask this on the mailing list, but should I just open a bunch of issues for each of the modifications that would together define the addition?

**Comment by aebrahim** [comment]
Would renaming Metabolite to something else work?

I am writing my own ME code and started with

from cobra import Metabolite as Component

**Comment by afif-elghraoui** [comment]
I guess so. What I did was move the Metabolite properties having to do with simulation results up to the Species class, but that's basically the same thing as renaming Metabolite and getting rid of Species.

**Comment by aebrahim** [comment]
Ok good to know. Thanks for voicing your concern... Don't want to break
features people depend on
