### ISSUE TITLE
Reading and writing a SBML model adds the compartment to metabolite names

### ISSUE THREAD

**Issue by cossio** [opencobra/cobrapy#149]
For example, if I load the E. Coli metabolic network (you can use any file you want):

ec = cobra.io.read_sbml_model("Ec_iJR904_GlcMM.xml")
cobra.io.write_sbml_model("Ec_iJR904_GlcMM_2.xml")
ec1 = cobra.io.read_sbml_model("Ec_iJR904_GlcMM_2.xml")

then Ec_iJR904_GlcMM_2.xml has all metabolite names suffixed with the compartment name. For example, h2o_c becomes h2o_c_Cytosol. Why does this happen? How can I fix it?

My cobra.__version__ is 0.3.0b3.
The file Ec_iJR904_GlcMM.xml is available here: http://benheavner.com/systemsbio/images/0/07/Ec_iJR904_GlcMM.xml.

**Comment by aebrahim** [comment]
The reason this is happening is because the metabolite compartment is "Cytosol" when it should be "c". When writing out SBML, to ensure compartmentalized metabolites are unique, cobrapy is trying to ensure the metabolite id ends with the compartment. Because it ends with "_c" and not "_Cytosol", "_Cytosol" is appended.

A workaround is to do the following:

```python
import cobra

ec = cobra.io.read_sbml_model("Ec_iJR904_GlcMM.xml")

for met in ec.metabolites:
    met.compartment = met.id[-1]
    
cobra.io.write_sbml_model(ec, "Ec_iJR904_GlcMM_2.xml")
ec1 = cobra.io.read_sbml_model("Ec_iJR904_GlcMM_2.xml")
```

It will be hard to fix this in a generic way I think because "c" won't necessarily correspond to the exact string "Cytosol" every time.
