### ISSUE TITLE
Cobrapy in jessie-backports is broken

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#186]
python3-cobra in jessie-backports is practically empty see https://packages.debian.org/jessie-backports/amd64/python3-cobra/filelist

whereas in the stretch version everything is fine
https://packages.debian.org/stretch/amd64/python3-cobra/filelist

**Comment by aebrahim** [comment]
The Debian packages were made by @afif-elghraoui

**Comment by aebrahim** [comment]
@afif-elghraoui do you have any idea why this might be the case?

**Comment by afif-elghraoui** [comment]
Hi,

On الأربعاء  7 تشرين الأول 2015 15:14, Christian Diener wrote:
> python3-cobra in jessie-backports is practically empty see
> https://packages.debian.org/jessie-backports/amd64/python3-cobra/filelist
> 
> whereas in the stretch version everything is fine
> https://packages.debian.org/stretch/amd64/python3-cobra/filelist
> 

I'm very sorry for missing this. I'm not sure why this happened, but I
will check into it. The python2 package was assembled just fine, so it
looks like the problem is just with the python3 package builder on jessie.

Since this is purely a packaging issue, we should probably move this off
Ali's issue tracker and to debian-backports@lists.debian.org (which I'm
including in this email now).

apologies and regards
Afif

-- 
Afif Elghraoui | عفيف الغراوي
http://afif.ghraoui.name

**Comment by cdiener** [comment]
Wow, you guys are quick. Thanks for looking into it. Either way those packages were still for b4 which still had the cplex python3 bug. It will be more importante for the b5+ packages which work well with python3.

**Comment by afif-elghraoui** [comment]
I just uploaded a corrected package. It should be available in a few hours or so. Hopefully, there won't be any more issues, but if there are, problems with Debian stable-backports are technically supposed be reported on the backports mailing list.

Thanks for pointing out the issue

**Comment by aebrahim** [comment]
Thanks for fixing this so quickly

**Comment by cdiener** [comment]
Thanks also from my part. Will test in the next days on my docker setups.
