### ISSUE TITLE
python 3 compatability

### ISSUE THREAD

**Issue by cfblaeb** [opencobra/cobrapy#190]
The following lines fail when installing on python 3.
I believe the excepts need to be changed to:
except Exception as e
and the print needs parenthesis'

cobra/solvers/glpk_solver_java.py", line 86
except Exception, e1

cobra/solvers/cplex_solver_java.py", line 318
print '%s failed: %s'%(solver_name, status)

cobra/solvers/gurobi_solver_java.py", line 73
except Exception, e:

**Comment by aebrahim** [comment]
Hello, and thanks for the bug report.

These files are only there to support jython (which is deprecated), which afaik only supports python 2.

Could you please give me more details about how you are encountering this failure? I'm not sure how this code would run on python 3.

Please include:

Operating System
Python type
Python version

Thanks.

**Comment by afif-elghraoui** [comment]
I raised this issue before in <https://github.com/opencobra/cobrapy/pull/165#issuecomment-111742078>. 

At least for the Debian package, the presence of these files prevented the Python3 version of the package from installing (see the Debian bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792058 ) for what happens when they are included there.  It's not a problem there anymore, but I thought this information might be helpful.

**Comment by aebrahim** [comment]
OK I see what's going on... even if these files aren't being run, the compiling to bytecode is failing for them.

I've merged #165 to fix this.

Thanks both of you for raising the issue.
