### ISSUE TITLE
Some weirdness in the new docs for summaries

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#238]
There are some weird results in the docs for the summary functions.

Looking at [section 4.3.1](http://cobrapy.readthedocs.org/en/latest/simulating.html#Running-FVA-in-summary-methods) the FVA flux for the objective value is "0.000" even though in [section 4.1.1](http://cobrapy.readthedocs.org/en/latest/simulating.html#Analyzing-FBA-solutions) it has been been established that the optimal value is "0.874". Also in "In[16]" below the pfk flux percentages are both 50% even though the reactions have different fluxes but the same stoichiometry...

**Comment by aebrahim** [comment]
Pinging @pstjohn

**Comment by pstjohn** [comment]
Strange, I'll take a look today.

On Mar 15, 2016, at 2:17 PM, Ali Ebrahim <notifications@github.com> wrote:

Pinging @pstjohn <https://github.com/pstjohn>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/opencobra/cobrapy/issues/238#issuecomment-197003964>

**Comment by pstjohn** [comment]
OK, so the answer to both issues is that the model hasn't been solved since the objective was changed to/from ATP maintenance. Its an easy fix, we just have to re-optimize before calling the summary method again. I'll put in a pull request.

More generally, If we wanted this to throw an error the best way might be to delete the existing solution whenever the objective value is changed. Otherwise we'll have to check whether or not the solution in model.solution indeed corresponds to the current objective value.

**Comment by aebrahim** [comment]
I've created #240 to track some improvements to summary.

**Comment by cdiener** [comment]
Ok thanks!

**Comment by aebrahim** [comment]
Did #239 fix this?

**Comment by cdiener** [comment]
Only the biomass value, not the percentages.

**Comment by cdiener** [comment]
Fixed with #271.
