### ISSUE TITLE
Failed test - test_single_gene_deletion with anaconda and python 3.5

### ISSUE THREAD

**Issue by ryanmames** [opencobra/cobrapy#245]
After installing cobrapy using pip, at the python command prompt  I run:

```
from cobra.test import test_all
test_all()
```
I get a single test failure, 5 skipped tests and 2 expected failures!

```
======================================================================
FAIL: test_single_gene_deletion (cobra.test.flux_analysis.TestCobraFluxAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):

  File "/Users/ra381/anaconda/lib/python3.5/site-packages/cobra/test/flux_analysis.py", line 129, in test_single_gene_deletion
    self.assertEqual(statuses[gene], 'optimal')
AssertionError: 'solsta.near_optimal' != 'optimal'
- solsta.near_optimal
+ optimal
---------------------------------------------------------------------
Ran 141 tests in 13.259s
FAILED (failures=1, skipped=5, expected failures=2)
True
```

**Comment by cdiener** [comment]
Checking the code base I am suspecting that you are using Mosek, could that be correct? 

In this case this would be due to the solver implementation not handling the "near_optimal" case ([which is currently not done](https://github.com/opencobra/cobrapy/blob/8ee13b458148d56f69690464cb8b5e67b000748e/cobra/solvers/mosek.py#L20)). 

If you have cplex or gurobi available this should not happen with those. 

Either way we should fix it for Mosek. It's kind of weird that Mosek defines a "near_optimal" state. The easiest solution would be to handle it as optimal. Does somebody have Mosek license to check whether this would work (@aebrahim)?

**Comment by ryanmames** [comment]
I could be using Mosek - I also have glpk installed (I think it should use
your supplied binding) and I'm not sure how to tell which optimiser is
being used. Is there a simple way that I can check this? Or force cobrapy
to use glpk and see whether the test is passed?

**Comment by aebrahim** [comment]
Can you do

import cobra
print(list(cobra.solvers.solver_dict.keys()))

**Comment by aebrahim** [comment]
This would also be helpful

```python
import cobra
print(cobra.solvers.get_solver_name())
```

**Comment by cdiener** [comment]
Cglpk never exposes anything that is named 'solsta' so I think it's unlikely that it's coming from there. Also, I have the same setup only with gurobi and cplex with Python 3.4 and those tests pass so I think it's not related to cglpk, cplex or gurobi....

**Comment by ryanmames** [comment]
So if I use

import cobra
print(list(cobra.solvers.solver_dict.keys()))

I can see that cglpk and mosek are installed. If I then run

print(cobra.solvers.get_solver_name())

It return cglpk

Checking the tests I still see that test_single_gene_deletion fails with
the same error message.

**Comment by aebrahim** [comment]
I think this is error is happening when using MOMA to do the gene deletions

**Comment by cdiener** [comment]
Exactly. I got a trial key for Mosek and made a reproducible example
-> https://gist.github.com/cdiener/b1eec270bb315735e43836bbfc890bf7

As I suspected above the problem is the missing ahndling for "solsta.near_optimal".
I'll make a pull request and I also think we should split up `test_single_gene_deletion` into two functions.

**Comment by aebrahim** [comment]
Separate test functions is a good idea.

Thanks for looking into it
