### ISSUE TITLE
problem using palettable with phenotypic phase plane plots

### ISSUE THREAD

**Issue by shlicshlac** [opencobra/cobrapy#255]
If the **palettable** package is installed, method _plot_matplotlib()_ in **cobra.flux_analysis.phenotype_phase_plane** will make a call to method _get_map_ in **palettable.colorbrewer** (line 72):
`color_list = get_map(theme, 'Qualitative', n_segments).hex_colors`
If n_segments is not in the range expected for the given colormap type and theme, _get_map_ raises a ValueError:

```
File "/usr/lib/python3.5/site-packages/cobra/flux_analysis/phenotype_phase_plane.py", line 73, in plot_matplotlib
    color_list = get_map(theme, 'Qualitative', n_segments).hex_colors
  File "/usr/lib/python3.5/site-packages/palettable/colorbrewer/colorbrewer.py", line 182, in get_map
    raise ValueError(s)
ValueError: Invalid number for map type 'Qualitative' and name 'Pastel1'.
Valid numbers are : [3, 4, 5, 6, 7, 8, 9]
```
If palettable is not installed, a default list is assigned color_list instead, and if n_segments is larger than the lengths of this list, the user gets a warning that there aren't enough colors to use, and the plot is still generated. To be consistent with the _plot_matplotlib()_'s behavior when palettable is not installed, when n_segments is too large and palettable is installed it should still give the same warning. This can be fixed by changing lines 66-72 in method _plot_matplotlib()_ in **cobra.flux_analysis.phenotype_phase_plane** from
```
        # pick colors
        if get_map is None:
            color_list = ['#A6CEE3', '#1F78B4', '#B2DF8A', '#33A02C',
                         '#FB9A99', '#E31A1C', '#FDBF6F', '#FF7F00',
                         '#CAB2D6', '#6A3D9A', '#FFFF99', '#B15928']
        else:
            color_list = get_map(theme, 'Qualitative', n_segments).hex_colors
```
to

```
        # pick colors
        color_list = ['#A6CEE3', '#1F78B4', '#B2DF8A', '#33A02C',
                      '#FB9A99', '#E31A1C', '#FDBF6F', '#FF7F00',
                      '#CAB2D6', '#6A3D9A', '#FFFF99', '#B15928']
        if not get_map is None:
            try:
                color_list = get_map(theme, 'Qualitative', n_segments).hex_colors
            except ValueError:
                from warnings import warn
                warn('palettable could not be used for this number of phases')
                    
```

**Comment by aebrahim** [comment]
Thanks for posting this bug report! I'll look into this.
On Jun 10, 2016 2:51 PM, "shlicshlac" <notifications@github.com> wrote:

If the *palettable* package is installed, method *plot_matplotlib()* in
*cobra.flux_analysis.phenotype_phase_plane* will make a call to method
*get_map* in *palettable.colorbrewer* (line 72):
color_list = get_map(theme, 'Qualitative', n_segments).hex_colors
If n_segments is not in the range expected for the given colormap type and
theme, *get_map* raises a ValueError:

File "/usr/lib/python3.5/site-packages/cobra/flux_analysis/phenotype_phase_plane.py",
line 73, in plot_matplotlib
    color_list = get_map(theme, 'Qualitative', n_segments).hex_colors
  File "/usr/lib/python3.5/site-packages/palettable/colorbrewer/colorbrewer.py",
line 182, in get_map
    raise ValueError(s)
ValueError: Invalid number for map type 'Qualitative' and name 'Pastel1'.
Valid numbers are : [3, 4, 5, 6, 7, 8, 9]

If palettable is not installed, a default list is assigned color_list
instead, and if n_segments is larger than the lengths of this list, the
user gets a warning that there aren't enough colors to use, and the plot is
still generated. To be consistent with the *plot_matplotlib()*'s behavior
when palettable is not installed, when n_segments is too large and
palettable is installed it should still give the same warning. This can be
fixed by changing lines 66-72 in method *plot_matplotlib()* in
*cobra.flux_analysis.phenotype_phase_plane* from

        # pick colors
        if get_map is None:
            color_list = ['#A6CEE3', '#1F78B4', '#B2DF8A', '#33A02C',
                         '#FB9A99', '#E31A1C', '#FDBF6F', '#FF7F00',
                         '#CAB2D6', '#6A3D9A', '#FFFF99', '#B15928']
        else:
            color_list = get_map(theme, 'Qualitative', n_segments).hex_colors

to

        # pick colors
        color_list = ['#A6CEE3', '#1F78B4', '#B2DF8A', '#33A02C',
                      '#FB9A99', '#E31A1C', '#FDBF6F', '#FF7F00',
                      '#CAB2D6', '#6A3D9A', '#FFFF99', '#B15928']
        if not get_map is None:
            try:
                color_list = get_map(theme, 'Qualitative',
n_segments).hex_colors
            except ValueError:
                from warnings import warn
                warn('palettable could not be used for this number of phases')


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opencobra/cobrapy/issues/255>, or mute the thread
<https://github.com/notifications/unsubscribe/ABUPSFihkLcwhXKP8G_bQ1_Mc5wYAezlks5qKc46gaJpZM4IzUcv>
.

**Comment by shlicshlac** [comment]
No problem. Thanks for working on COBRApy!!
