### ISSUE TITLE
coverage calculations are wrong

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#347]

**Comment by cdiener** [comment]
Just to have it one place: the cause for that is that the CI run the tests with

```python
from cobra.test import test_all
test_all()
```

The first import imports all the tests and their dependencies and the tests are run afterwards. As a consequence modules are not imported anymore in `test_all()` because they are already in the namespace. Due to this py.test considers the imports not to be tested and marks all function definitions (not their body) as missed.
