### ISSUE TITLE
refactor gapfilling / update  hints

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#383]

**Comment by cdiener** [comment]
How relevant are those methods today where most people use one of the full-fledged reconstruction algorithms like the ones in ModelSeed, Gimme, t-init, CORDA, etc. Especially since we already decided that reconstruction in general should happen in its own packages? 

If we keep it I would like the API to be more permissive. For instance the requirement that reactions from the "filler candidates" can not be in the model already makes it pretty complicated to use.

**Comment by pstjohn** [comment]
Agreed, this wouldn't be high up on my list of priorities. I'm fine with losing some functionality with the 0.6 release, if it's requested later we could always come back to it.

**Comment by hredestig** [comment]
Alright, agreement here, let's drop this one

**Comment by mmundy42** [comment]
Just FYI, gapfilling is something I may experiment with later but agree that it can be removed for now.

**Comment by hredestig** [comment]
I'm re-opening this one on popular request. If there are near perfect matches in other packages, let's link to those, otherwise let's refactor growMatch and SMILEY so they work with optlang (and perhaps later on then move to a different package).

**Comment by mmundy42** [comment]
Thanks for reopening this issue. We were just talking about how to handle gapfilling at our lab meeting this week and having those options would really help.

**Comment by gregmedlock** [comment]
FWIW I am still using 0.5.8 strictly because of access to SMILEY/growmatch, so I would be grateful to see it in a future release.

**Comment by cdiener** [comment]
I agree that it should be included given the high interest. I would propose some small changes to the API to overcome some limitations:

- instead of having growMatch and Smiley separate refactor into a single function that takes an objective (reaction, expression, etc)
- handle the universal model more gracious, for instance allow it to include reactions that are part of the model already
- alternatively use the standard from many other reconstruction algorithms and only have one universal model and a list of reactions that should be included
- handle the case where an objective requires removal of reactions from the model rather than addition of reactions from the universal model (might be out of scope for gapfilling). 

Ideally cobrapy would not need to implement gapfilling since many of the current gapfilling methods deal with it, however many of those are not available in Python or are not maintained anymore. 

Final shameless plug: our [CORDA](https://github.com/cdiener/corda) package (based on the work of Schultz and Qutub) can solve all the use cases presented here and will be faster than any MIP formulation.

**Comment by hredestig** [comment]
#497 fixes this including all @cdiener 's comments minus the reaction removal which can be handled in a different PR

**Comment by hredestig** [comment]
closed with #497
