### ISSUE TITLE
refactor loopless model

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#385]

**Comment by cdiener** [comment]
I would take that one if nobody else has started already. I would like that to be similar to MOMA so you can do something like:

```python
with model:
  loopless(model)
  model.optimize()
  single_reaction_deletion(model)
```

So you can plug-and-play it with other methods.

**Comment by cdiener** [comment]
Ok reading up on that, there seem to be various methods to get loopless solutions. The one implemented now is the original one from Schellenberger which adds a lot of MIP constraints to the model. There also *a posteriori* methods like CycleFreeFlux which can transform a "normal" FBA solution to a loopless one. Those do not require integer variables or constraints and are faster. However, CycleFreeFlux requires its own FVA function if we want this.

**Comment by pstjohn** [comment]
What's the difference between CycleFreeFlux and parsimonious FBA?
I'd probably prefer the version that doesn't use the MIP constraints: that was a big limitation in me using the methods at least. (cplex availability and all that)

**Comment by cdiener** [comment]
Excellent question. It's pretty close but it looks for a solution that is a bit closer to the previous ones. In particular the solution from CycleFreeFlux will

- have the exact same exchange fluxes
- have the same sign in all fluxes as the original solution

For the FVA version it actually gets the solution with minimal/maximal cycle free flux. This can't be done with pFBA because if you set a single flux as maximization objective it may still give you cycles with that particular flux, even though all other fluxes won't have cycles.

Doesn't glpk do MIP as well?

**Comment by cdiener** [comment]
Pretty much done in #391. Just have to discuss the API a bit.
