### ISSUE TITLE
refactor double deletion

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#390]

**Comment by cdiener** [comment]
Hi I didn't start on this because there were some issues I didn't really have an immediate solution. Basically:

1. Double deletion use their won ProcessPool which is pretty much the same as `multiprocessing.Pool` only that it does not work on Windows whereas the standard lib one does. So maybe we should port it to the Python one to have less code to maintain.

2. Usually if you distribute stuff across processes in Python all arguments to the process are pickled and broadcast to the correct process. That creates quite some overhead so you want the individual processes to do long computations. For double deletions you could, for instance, fix the first reaction for the deletion (r1) and than compute all double deletions for the cross with all others r1 x r2, r1 x r3, ... in one process.

3. Due to the pickling I am not sure what happens to the optlang `optlang.Model.problem` which in many cases is a pointer to the lower level problem in C (at least for GLPK). If the Pool only broadcasts the pointer and not a newly created C object all hell breaks loose since multiple processes will write to the same C struct and GLPK is *not* thread safe.

4. Results for double deletions are currently kept in sparse matrices which requires scipy. Maybe would be good to offer a version that does not require it like a dict of dicts (deletions["r1"]["r2"] = growth_rate) and have helper functions that conver those to scipy matrices or pandas DataFrames if installed.

**Comment by KristianJensen** [comment]
Regarding 3: Optlang models are picklable and can thus be used without problems in parallel processes (cameo has a few functions that do this). I'm not sure however what would happen if you tried to use them in parallel threads, but usually you wouldn't do that anyway due to the GIL.

**Comment by cdiener** [comment]
Thanks @KristianJensen. That resolves one of the doubts. You are correct: we are not using threads :+1:

**Comment by Midnighter** [comment]
@cdiener Henning and I decided that this issue has priority and therefore I have assigned myself.

**Comment by Midnighter** [comment]
Can you elaborate a little on the Windows issue, please? What exactly doesn't work? I'm wondering since the cobra code is such a thin wrapper around the `multiprocessing` objects.

**Comment by cdiener** [comment]
I remember we had problems with the cobra pool on conda windows builds (actually that was the reason why we never succeeded in having a Windows package). At some point Ali just hardcoded that the cobra Pool would fall back to a (non-parallel) mock pool on windows. 

I think we should use the "official" Pool from standard lib. Flux sampling uses it and it works on all OSs. Just keep in mind that Unix and Windows create processes very differently. So the functions you send to the pool should have all needed objects in their arguments since only Unix processes have access to globals.

**Comment by cdiener** [comment]
Any news on that?

**Comment by Midnighter** [comment]
Had abandoned this for a while, sorry. Thanks for the poke. I will pick up the work again and would like to generalize this to `N`-deletion.
