### ISSUE TITLE
Move or add summary functions to the Solution class.

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#449]
I don't have all the details worked out in my mind yet but I strongly feel that the `Solution` class (and maybe an anologous `FVASolution` class) should receive `summary` methods. The simple summary case should already be possible easily. Instead of relying on current solver state it would use values of the solution instance.

The FVA extended summary is a little more tricky, on one hand it could take a stored solution and the current model state, perform FVA and create a summary. On the other hand one could say the user should perform an FVA first, and can then get a more rich summary from the `FVASolution`.

Anyway, just writing down a thought so I don't lose it.

**Comment by cdiener** [comment]
How would that work without introducing a back reference to the model in the solution class? The summary methods currently need a cobra model to identify consuming and producing reactions, so you can not generate a summary just from the solution itself. Or maybe I just did not understand it well :sweat_smile:

**Comment by pstjohn** [comment]
I can see where your going with this, I for one am confused where and how a model carries around its most recent solution, how that does (or should) interact with the context stack, etc.

As @cdiener said, the summary methods do need to know pretty much the whole model structure. The API of `model.summary()`, `model.metabolites.met.summary()` is nice too, and would be too bad to loose. But other than a `SolvedModel` class, I'm not sure how you'd integrate those two classes otherwise.

**Comment by Midnighter** [comment]
In retrospect it's probably not that great of an idea. I was thinking that it might be useful to get some broad insight into what a solution looks like. Since they are `pandas.Series`, however, you can already ask for `Solution.fluxes.describe()` and that's pretty much what I meant.

Unless someone has another idea on this issue, I'm happy to close it.

**Comment by hredestig** [comment]
closing this with #566
