### ISSUE TITLE
x_dict as pd.Series

### ISSUE THREAD

**Issue by zakandrewking** [opencobra/cobrapy#515]
It came up recently (https://github.com/zakandrewking/escher/issues/183) that `solution.x_dict` in COBRApy 0.6 is a pandas Series. We can support this with an update to Escher, but I wanted to ask here first: 

Do you think it will confuse users who expect a dictionary, because `x_dict` sounds like a dict? Would `x_series` or equivalent be a better name for the pandas Series?

Thanks!

**Comment by cdiener** [comment]
That is a good point. Currently, `x_dict`, `y_dict` and `f` are flagged as deprecated in favor of the new `fluxes`, `reduced_costs` and `objective_value` ([full API](https://cobrapy.readthedocs.io/en/latest/cobra.core.html#module-cobra.core.solution)). 

So I would recommend to use those attributes because they are guaranteed to stay for the next releases. 

For JSON serialization something like

```Python
sol = model.optimize()
sol.fluxes.to_json("solution.json")
```
should work.

**Comment by zakandrewking** [comment]
Ok perfect. That's easy to support

**Comment by zakandrewking** [comment]
Will `.fluxes` always have a float type, or should I explicitly check for None in the series?

**Comment by Midnighter** [comment]
`None` values were only occurring with reduced costs of MILP problems because optlang inserted them. We check for that differently now and I can't think of a case where you would see non-float values. If that should ever be the case then both `pandas.Series.notnull` and `numpy.isfinite` provide easy Boolean masks to deal with those.

**Comment by hredestig** [comment]
I guess this issue is solved? If not please re-open
