### ISSUE TITLE
Implement quick-optimization function

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#540]
We need a method on model to do what `model.optimize` does but which doesn't create a full solution to avoid the need for calling `model.solver.optimize` directly, and provide a method that we can document and explain when to use.

Could be implemented something like
```
def quick_optimize(self, value=0.):
    model.solver.optimize()
    try:
        assert_optimal(model)
        return model.solver.objective.value
    except OptimizationError:
        return value
```

An alternative would be to just provide better docs in the notebook for  how/when to use `model.solver.optimize`

Thoughts?

**Comment by Midnighter** [comment]
How about that being the default `Model.optimize` and only letting the optimization functions fba, pFBA, FVA, etc. return a solution object?

**Comment by pstjohn** [comment]
I think this is partly related to #520 sadly, maybe we should have another video chat to iron those out. Maybe focus on the present and future use of the `Solution` class...

Would the workflow be `model.quick_optimize`, followed by `model.reaction.xyz.flux` to grab the flux values?

**Comment by cdiener** [comment]
I am not sure, but I have a *deja vu*, like we already discussed this before and one of the arguments was that having several optimize functions would be less obvious (Python Zen etc.). We could also have one solution object however that allows some attributes to be None. For instance default is only to have fluxes and objective value and you can control whether you also want shadow_fluxes etc. by keyword args. `quick_optimize` looks a bit too small to me to be it's own function. You can do the same thing already with:

```Python
model.solver.optimize()  # returns solver status as a string so you know whether it's been optimal
model.objective.value
```
which seems fine to me.

@pstjohn yes that would work, but if you want to grab several fluxes at once `get_solution` might actually be faster since it uses function that grab all primals in the C interface and just reformats them to correspond to fluxes.

**Comment by pstjohn** [comment]
Exactly. I meant more from the standpoint of someone who might be using `model.solver.optimize()`

**Comment by hredestig** [comment]
The main advantage of having a method, or method parameter, would be to have somewhere to add doc string that can be seen when you browse the Model class. Currently the existence of `model.solver.optimize` is not so obvious. But, as suggested, could also be added to some notebook as well. Baking it into `model.optimize` is a good (maybe better) option as well I think.
@pstjohn Yes, that makes sense to me and also what is currently mostly used..

Anyway a video chat would indeed help to move forward here, so jot down your availability please (uses timezones so should be native to you otherwise it's 16, 17 or 18 Copenhagen time)

https://doodle.com/poll/wccs36e39zt9x6vz
