### ISSUE TITLE
Add the method for loopless FVA from cameo

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#590]
cameo uses a different method for removing cycles in the FVA result. I ran this on iJR904 and cobra takes 3 min whereas cameo 15 s.

**Comment by cdiener** [comment]
They use exactly the same method, but I will look into what is making the cobrapy version so slow...

**Comment by cdiener** [comment]
Okay, I checked it and there is actually something weird going on in cameo. For now cameo only checks reactions for cycles if the flux is larger than 666 (?). For the textbook model that only applies to 4 reactions. Obviously that will not work for any model which as maximum bounds smaller than that and ,even if not, it is not guaranteed to remove cycles at all due to that restriction. Calling it directly without the sloppy argument, ergo `_cycle_free_fva(mod, sloppy=False)` is actually slower than the cobrapy implementation...

**Comment by Midnighter** [comment]
@phantomas1234 can you comment on this condition? It seems rather odd to check for diabolic flux bounds.

**Comment by phantomas1234** [comment]
I am sorry for the satanic and arbitrary threshold here. I'll need to check my implementation, but if I remember correctly what I did was to introduce  `sloppy` to check if reactions are in cycles only if they have a large flux (to speed up cyclefreeflux). Setting `sloppy=False` makes it indeed very slow (I never really understood why tbh). Doesn't `sloppy` make sense though? Wouldn't most cycles have very large fluxes? Also, I've yet to see a model to have default bounds < 1000 (I agree though that sloopy should probably be based on some actual bound in the model). The textbook model has only one cycle and it is detected even when `sloppy=True`. @cdiener are you referring to the toy example on the docs regarding the cycle that is not close to the reaction bounds?

**Comment by cdiener** [comment]
Thanks for the reply @phantomas1234 :)

I agree that not many models have flux bounds different from 1000 but I think it would be a pretty strong assumption to make about any model. For instance models constrained with fluxome data would deviate from that assumption... 

I referred to the Salmonella example from the [docs](https://cobrapy.readthedocs.io/en/latest/loopless.html#Loopless-solution) (first plot). This plots the loopy fluxes vs the loopless fluxes in the Salmonella model and you can see that most differences occur in small flux values. This seems to happen if you have several connected cycles. For instance if two cycles connect into substrates for another reaction you will have something like `v_other = v_in,1 + v_in,2 + ...` since `v_other` has an upper bound of 1000 so `v_in,*` will have to have fluxes <= 1000 which will limit the flux that can be channelled through the cycle.

CycleFreeFlux is much much faster than the Schellenberg method (several orders of magnitude). I would not say it is slow per se since a single run of CycleFreeFlux takes about 250ms for the E coli model. The problem is that in FVA we have to run 2*n_r optimizations. Which for the E coli model results in roughly 22 minutes (which is pretty close to the actual computation time, with symengine its 15min). The major limit here is transporting fluxes between the C interface and Python. However, that is simply the overhead of creating the Python object and filling it with the values. So you could only avoid it by directly implementing the entire FVA in C I feel :(

**Comment by cdiener** [comment]
@Midnighter @ChristianLieven for the particular use case of memote I think a good heuristic would be maximizing sum (abs(v)) for all fluxes with finite bounds. That should trigger most of the actual cycles, however there is no guarantee that it finds all of them. You could also just report the active cycles when maximizing the biomass.

**Comment by matthiaskoenig** [comment]
Upper bounds of 1000 are completely arbitrary and should in no way be used
hard coded in any algorithm. Just because BiGG decided this is how to
handle bound does not mean that it is a good idea. Normally this should be
INF because this is what it means in reality, i.e. we have no idea what the
bounds are so lets just set an arbitrary value. But in reality if you dont
have any idea the problem is unconstrained. Getting off topic here.
Just dont hardcode 1000, provide an option to set the bound default or
bound algorithm value. Read ot from one global setting ! and use it
everywhere you use this arbitrary bound. For instance also in teaction
default bounds. One should be able to set this global default bound in
cobra.

COBRA_DEFAULT_BOUND = 1E6

or to whatever value. As soon as I have fluxes in different units I need to
change this value to have consistant behavior betwwen models with different
flux units.

**Comment by Midnighter** [comment]
Implementing a global configuration object is on my list.

@cdiener @phantomas1234 are we happy with loopless FVA in cobrapy? Is there something we should still adapt from cameo?

**Comment by cdiener** [comment]
It should more or less have feature parity with cameo. There are some general problems with the method though that are discussed in #698.

**Comment by Midnighter** [comment]
@matthiaskoenig a global configuration object has landed on the devel branch. Any loopless discussion should continue in #698, I suppose.
