### ISSUE TITLE
How to check whether a sample is well-mixed (Just like mixFraction() in CobraToolbox)

### ISSUE THREAD

**Issue by WuyangFF95** [opencobra/cobrapy#615]
#### Problem description
I was using the sampling method in the CobraPy 0.9.0 to generate a sampling matrix with 10,000 sampling vectors using OptGpSampler. But I don't know how to check whether these vectors are sparsely distributed (well-mixed) in the sample space. In CobraToolbox, it has a mixFraction() function to compare two sets of sampled points and determines how mixed they are.

Another problem is, how can I utilize the class cobra.flux_analysis.sampling.Problem? The document doesn't contain much detail. 

Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.
import cobra
dn_raw = cobra.io.load_matlab_model(".../dn_raw.mat")
raw_samp = cobra.flux_analysis.sample(dn_raw,10000)
```

#### Output of `cobra.show_versions()`

<details>
# Paste the output of `import cobra;cobra.show_versions()` here.
System Information
==================
OS                         Windows
OS-release                       7
Python                       3.6.3

Package Versions
================
pip                          9.0.1
setuptools     36.5.0.post20170921
cobra                        0.9.0
future                      0.16.0
swiglpk                      1.4.4
optlang                      1.2.3
ruamel.yaml                0.15.34
pandas                      0.20.3
numpy                       1.13.3
tabulate                     0.8.1
python-libsbml              5.15.0
lxml                         4.0.0
scipy                       0.19.1
matplotlib                   2.1.0
palettable                   3.1.0
pymatbridge                  0.5.2
</details>

**Comment by cdiener** [comment]
There are several strategies to judge whether a sampler has converged. The ones I used before to benchmark the cobrapy solver can be found [here](https://github.com/cdiener/cobra-docker/blob/master/sampling_benchmark.ipynb). As far as I understand the mixing fraction is only a heuristic and there are cases where it does not work too well (for instance if you get trapped in a subspace). It would be trivial to implement. For instance the following would basically be the same as the matlab version (assuming both samples have the same size):

```Python
def mixfrac(x, y):
    return ((x > x.median()) == (y > y.median())).mean().mean()
```

This one gives me a mixing fraction of 0.52 for two different samples of size 1000 for the `textbook` model. 

Methods that specifically integrate the variance of the sampling are probably better. I have seen many people use the Gelman-Rubin statistic but since the samplers are not really Markovian I would say that checking for histogram convergence is probably the most robust method.  

The `Problem` type is documented [here](https://cobrapy.readthedocs.io/en/stable/cobra.flux_analysis.html#cobra.flux_analysis.sampling.Problem) but is not supposed to be used unless you want to implement your own sampler. It basically contains the entire formulation of the sampling problem such as equality and inequality constraints, homogeneous variables, projections etc. If you just want to sample from a model you will never need to touch those. Rather you would use the sampling classes [as described in the docs](https://cobrapy.readthedocs.io/en/stable/sampling.html#Advanced-usage).

**Comment by WuyangFF95** [comment]
Thanks very much!
