### ISSUE TITLE
using slim_optimize instead of optimize returns a different result when filtered for a specific purpose

### ISSUE THREAD

**Issue by synchon** [opencobra/cobrapy#635]
#### slim_optimize() provides a different value of result when filtered for synthetic lethal analysis

Hello,
I am analyzing synthetic lethal reactions and I used ```optimize```. It gives me the proper value but when I am optimizing the code I use ```single_reaction_deletion``` which uses ```slim_optimize``` under the hood. I cross-checked it by swapping out ```optimize``` for ```slim_optimize```. It gave me the similar incorrect value. Is it some inefficiency in ```slim_optimize```?

```python
def singleSL(model,cutoff=0.01,eliList=None,atpm='ATPM'):
    '''
    Analysis for single lethal reactions
    '''
    if not eliList:
        eliList = [model.reactions.get_by_id(atpm).id]
    elif atpm not in eliList:
        eliList.append(model.reactions.get_by_id(atpm).id)

    solWT = model.optimize(objective_sense='maximize',raise_error=True)
    grWT = solWT.objective_value
    Jnz = solWT.fluxes.where(lambda x : x != 0.).dropna().drop(labels=eliList,errors='ignore').index
    Jsl = single_reaction_deletion(e_coli_model,reaction_list=Jnz)['flux'].where(lambda x : x < grWT * 0.01).dropna()

    return Jsl

```

#### Output of `cobra.show_versions()`

<details>

System Information
==================
OS           Darwin
OS-release   17.2.0
Python        3.6.1

Package Versions
================
pip           9.0.1
setuptools   36.7.2
cobra         0.9.1
future       0.16.0
swiglpk       1.4.4
optlang       1.2.5
ruamel.yaml 0.15.34
pandas       0.21.0
numpy        1.13.3
tabulate      0.8.1
lxml          4.1.1
scipy         1.0.0
matplotlib    2.1.0
pymatbridge   0.5.2

</details>

**Comment by Midnighter** [comment]
I'll have a look in a moment. For now I notice that in your code example the function accepts a `model` parameter but in the knockout you pass `e_coli_model`. Is that copy&paste mistake or is that your actual code?

**Comment by synchon** [comment]
It’s a copy and paste error.

**Comment by Midnighter** [comment]
Hey @synchon, a few more pieces are missing for me.
1. Which model were you using (in case that you can share)?
2. Your variable `Jsl` contains a flux distribution. So the output of what exactly was 277 vs 278?
3. Where did you replace `slim_optimize`? In this function of yours or you used `optimize` in the `single_reaction_deletion` function?

**Comment by cdiener** [comment]
`slim_optimize` and `optimize` use exactly the same code to obtain the objective value, only that `slim_optimize` does not get all the other values as well. Could you define what you mean by "proper" value. The solvers in cobrapy use [floating point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems) so values can differ between different runs by up to the solver tolerance (1e-6 by default). For the same reason the following line does not work either:

```Python
Jnz = solWT.fluxes.where(lambda x : x != 0.).dropna().drop(labels=eliList,errors='ignore').index
```

If the solver returns by the a value of 0.0 (unlikely), the real solution value would lie in [-1e-6, 1e-6], so it might not be "really zero". If you give us a reproducible minimal example we might help you to do what you want :)

**Comment by synchon** [comment]
@Midnighter
1. I am using E. coli iAF1260 model for the purpose. 
2. The Jsl is filtered by ```lambda x : x < grWT * 0.01``` 
3. This was my initial code before using ```single_reaction_deletion```. This gave me the correct value of 278.
```python
def singleSL(model,cutoff=0.01,eliList=None,atpm='ATPM'):
    '''
    Analysis for single lethal reactions
    '''
    if not eliList:
        eliList = [model.rections.get_by_id(atpm).id]
    elif atpm not in eliList:
        eliList.append(model.reactions.get_by_id(atpm).id)

    solWT = model.optimize(objective_sense='maximize',raise_error=True,solver='optlang-glpk')
    grWT = solWT.objective_value
    J = solWT.fluxes
    Jnz = np.flatnonzero(J)

    eliIdx = [model.reactions.index(reaction_id) for reaction_id in eliList]
    Jnz = np.setdiff1d(Jnz,eliIdx)

    Jsl_idx = []
    
    for delIdx_i in tqdm(Jnz,desc='Identifying Jsl'):
        with model as modeldel:
            modeldel.reactions[delIdx_i].bounds = (0.,0.)
            solKO_i = modeldel.optimize(objective_sense='maximize',solver='optlang-glpk')
            if solKO_i.objective_value < grWT * cutoff:
                Jsl_idx.append(int(delIdx_i))
    
    Jsl = model.reactions.get_by_any(Jsl_idx)
    return Jsl
``` 

@cdiener In that case will changing the solver give me an accurate result? Will it be helpful if I attach my model file and elimination list file?

**Comment by cdiener** [comment]
So I tried your two functions with the iAF1260 model and using all reactions as knockout candidates. The first function you posted returns 279 and the second one does not run (always returns an empty list for me). Running a stripped down version of what you are doing in your code I could identify the issue. The problem is that your initial function does not handle infeasible solutions correctly. If you knock out glucose import there is no possible solution that fulfills the >0 lower bound on the ATPM reaction. So there is no solution. However, if you call model.optimize without the `raise_error` flag it will still return the (infeasible) fluxes for debugging purposes. In this case it will give you a negative growth rate which obviously is a bounds violation and not a valid solution:

```Python
In [61]: with e_coli:
    ...:     e_coli.reactions.EX_glc__D_e.knock_out()
    ...:     print(e_coli.optimize().objective_value)
    ...:     
cobra/util/solver.py:419 UserWarning: solver status is 'infeasible'
-0.0586798390945658
```

As you see it actually warns you about the infeasibility. `single_reaction_deletion` handles this case correctly and returns NaN which is not captured by your filter (< 0.01 * growth_rate) which is the correct behaviour. Your initial function does not do that and uses the invalid -0.05 growth rate value. So I would think the error is in your initial function.

Regarding the prefiltering you do (flatnonzero etc.), this would only be valid with an exact solver which is currently not available in cobrapy (coming in the next release). However, that waould also be several orders of magnitude slower. In general not using the prefilter and using the optimized `single_reaction_deletion` will still be much faster (checking all reactions in your model takes about 2s for me).

**Comment by synchon** [comment]
I get it. It does show me the warning while running. It totally makes sense. What I intend to do is obtain the fluxes after the first optimization and then select the non-zero values from those fluxes and then take those remaining reactions as my ```reaction_list``` for ```single_reaction_deletion```. How would you suggest me to go about it?

**Comment by Midnighter** [comment]
![screenshot from 2017-12-05 09-51-15](https://user-images.githubusercontent.com/135653/33598183-204176c2-d9a2-11e7-9acb-f0ce448882a6.png)

Just replace with iAF1260 (or use the newer [iML1515](http://bigg.ucsd.edu/models/iML1515)). The last frame shows you one potential criterion for essentiality. You may choose a different threshold, of course (such as 1% of growth rate).

**Comment by synchon** [comment]
Ya this works great! I needed to work with pFBA rather than FBA. Thank you!

**Comment by cdiener** [comment]
pFBA will only make sense if you also extract all other fluxes. If you are only looking at the growth rate FBA and pFBA will always return the same value. 

Also note that line 6 does *not* guarantee that the excluded reactions have zero fluxes. They may still have non-zero fluxes in the range [0, 2e-6]. I would probably not run that exclusion at all. Just run `single_reaction_deletion` on all reactions instead of the filtered ones. It will still be fast.

**Comment by synchon** [comment]
For some weird reason, my ```objective_value``` for pFBA and FBA are varying.
![screen shot 2017-12-06 at 11 21 22 am](https://user-images.githubusercontent.com/13277639/33646867-ecabf3ec-da77-11e7-835b-fde1f2e1518c.png)
Actually, my algorithm demands that I operate on the non-zero fluxes rather than the total flux set. So, that is the reason I am trying to perform a pre-filtering.

**Comment by Midnighter** [comment]
The objective of pFBA is to minimize the sum over all fluxes. That is why you're seeing such a high value. In order to compare the two you need to record the ID of the biomass reaction (or whatever was your FBA objective) and retrieve that from the pFBA solution. Since pFBA fixes the lower and upper bound of that reaction to the value found by FBA they are guaranteed to be the same (as long as a feasible solution exists).

**Comment by synchon** [comment]
Yeah got it. I actually got confused in the working of pFBA.

**Comment by synchon** [comment]
The documentation reports that FBA and pFBA return almost the same value, but I'm getting a slight variation. Only when you check the flux of the biomass reaction, then only you get the proper value in case of pFBA. Is this the normal behaviour of the pFBA?
![screen shot 2017-12-06 at 4 29 19 pm](https://user-images.githubusercontent.com/13277639/33658530-0aa406ac-daa3-11e7-8384-886130875ef1.png)

**Comment by Midnighter** [comment]
As I tried to explain above this is expected. We could emphasize the fact that you need to get the flux for your objective but the code https://cobrapy.readthedocs.io/en/latest/simulating.html#Running-pFBA actually shows this.

**Comment by synchon** [comment]
Yeah, it makes sense now. Thank you!
