### ISSUE TITLE
Recursive additions and deletion of reactions leads to Model infeasability.

### ISSUE THREAD

**Issue by vilacelestin** [opencobra/cobrapy#641]
I'm trying to sequentially delete reactions from a model whilst preserving feasibility and came across an issue where the addition of a reaction that should restore feasibility to an infeasible model fails to do so.  

The following Code Sample should make this clear. I'll also upload the miscreant model

[model_test.xml.zip](https://github.com/opencobra/cobrapy/files/1553571/model_test.xml.zip)

```python
import cobra
from cobra.flux_analysis import *

weird = cobra.io.read_sbml_model("model_test.xml")

# .. now remove sequentially
weird.reactions.get_by_id('AMAOTr').lower_bound = 0
weird.reactions.get_by_id('AMAOTr').upper_bound = 0
weird.optimize() # grows

weird.reactions.get_by_id('CYSSADS').upper_bound = 0
weird.optimize() # grows

weird.reactions.get_by_id('UAGAAT').lower_bound = 0
weird.reactions.get_by_id('UAGAAT').upper_bound = 0
weird.optimize() # does not grow

# .. now restore bounds to wt in the reverse direction
weird.reactions.get_by_id('UAGAAT').lower_bound = -1000
weird.reactions.get_by_id('UAGAAT').upper_bound = 1000
weird.optimize() # does not grow!

weird.reactions.get_by_id('CYSSADS').upper_bound = 1000
weird.optimize() # does not grow!!

weird.reactions.get_by_id('AMAOTr').lower_bound = -1000
weird.reactions.get_by_id('AMAOTr').upper_bound = 1000
weird.optimize() # only now it grows!!
```

System Information

OS Linux
OS-release 4.4.0-83-generic
Python 2.7.12

Package Versions

pip 9.0.1
setuptools 29.0.1
cobra 0.8.2
future 0.16.0
swiglpk 1.4.4
optlang 1.2.1
ruamel.yaml 0.14.12
tabulate 0.7.7
python-libsbml 5.15.0
lxml 3.5.0

**Comment by Midnighter** [comment]
You're being hit by numerical instabilities due to the solver's feasibility tolerance. I have recorded each step that you perform above and one possible outcome is:

GLPK
![glpk_default](https://user-images.githubusercontent.com/135653/33931508-83942752-dff0-11e7-9605-ab4d22b80719.png)

CPLEX
![cplex_default](https://user-images.githubusercontent.com/135653/33931512-875cc4c0-dff0-11e7-9a47-946c12a045f2.png)

(The number you see is the default feasbility tolerance of the solver.)

Please note that the flux of AMAOTr is below the default tolerance right from the start. Also please note that the smallest stoichiometric coefficient in your model is dangerously close to the feasibility tolerance:
```python
from cobra.util import create_stoichiometric_matrix
import numpy as np

s = create_stoichiometric_matrix(model)
pos = np.abs(s)
pos[(pos > 0)].min()  # 1.9999999999999999e-06
```

Now observe what happens when you lower the tolerance:

GLPK
![glpk_lower](https://user-images.githubusercontent.com/135653/33931995-02c0fedc-dff2-11e7-8376-d6269b061e51.png)

CPLEX
![cplex_lower](https://user-images.githubusercontent.com/135653/33932004-0b703a70-dff2-11e7-94cd-08e5c421d62d.png)

In the following is my code. I'm using a context (`with model:`) so that changes are reverted when leaving the context.

```python
rows = list()
with model:
    biomass = model.reactions.BIOMASS_Ec_iJO1366_core_53p95M
    amaot = model.reactions.AMAOTr
    cyssads = model.reactions.CYSSADS
    uagaat = model.reactions.UAGAAT
    
    model.solver = "cplex"
    model.solver.configuration.tolerances.feasibility = 1E-9
    print(model.solver.configuration.tolerances.feasibility)
    model.slim_optimize()
    rows.append((biomass.flux, amaot.flux, cyssads.flux, uagaat.flux))
    
    amaot.knock_out()
    model.slim_optimize()
    rows.append((biomass.flux, amaot.flux, cyssads.flux, uagaat.flux))
    
    cyssads.knock_out()
    model.slim_optimize()
    rows.append((biomass.flux, amaot.flux, cyssads.flux, uagaat.flux))
    
    uagaat.knock_out()
    model.slim_optimize()
    rows.append((biomass.flux, amaot.flux, cyssads.flux, uagaat.flux))
    
    uagaat.bounds = -1000, 1000
    model.slim_optimize()
    rows.append((biomass.flux, amaot.flux, cyssads.flux, uagaat.flux))
    
    cyssads.upper_bound = 1000
    model.slim_optimize()
    rows.append((biomass.flux, amaot.flux, cyssads.flux, uagaat.flux))
    
    amaot.bounds = -1000, 1000
    model.slim_optimize()
    rows.append((biomass.flux, amaot.flux, cyssads.flux, uagaat.flux))

pd.DataFrame(rows, columns=(biomass.id, amaot.id, cyssads.id, uagaat.id))
```

**Comment by phantomas1234** [comment]
@Midnighter is the glpk exact solver already available in to cobrapy? That could be helpful to @vilacelestin.

**Comment by Midnighter** [comment]
Good point!

```python
import optlang

model.solver = optlang.glpk_exact_interface
```

Please be aware that the exact solver is slower, of course. For this problem it's still reasonably fast, though.

**Comment by cdiener** [comment]
This also works with a string:

```Python
model.solver = "glpk_exact"
```

We should add this to the docs...

**Comment by Midnighter** [comment]
It doesn't work quite yet because it's not in the list of expected solvers. It's a quick fix, though, and then we should add it to the docs indeed.

**Comment by Midnighter** [comment]
My bad, it actually works already in the latest release. I consider this issue solved. Feel free to re-open @vilacelestin.
