### ISSUE TITLE
Reverse biomass reaction added after model import

### ISSUE THREAD

**Issue by cvitlanko** [opencobra/cobrapy#726]
Hi, I am use cobra 0.13.0

I imported my model with model = cobra.io.read_sbml_model('path')

If I make a comand model it shows me :
`Name	emptyModelID
Memory address	0x0181d35b160
Number of metabolites	383
Number of reactions	405
Objective expression	-1.0*biomass_cho_reverse_073b2 + 1.0*biomass_cho
Compartments	Cytoplasm, Mitochondrion, Endoplasmic_reticulum, Extracellular, Peroxisome, unknownCompartment3`

In the xml file there is no biomass_cho_reverse.

I also tried 
`model.reactions.biomass_cho.reversibility
False`

I have not seen reverse reaction before in other models. Is it desired behavior?

**Comment by Midnighter** [comment]
Hey,
This is not explained very well in the docs. You can find a little bit in the part about [arbitrary constraints](https://cobrapy.readthedocs.io/en/latest/constraints_objectives.html). Basically, we automatically assign a forward variable and a reverse direction variable to each reaction in a model. This makes problems like pFBA easier to handle.

So there is 
`model.reactions.biomass_cho.forward_variable`
`model.reactions.biomass_cho.reverse_variable`
and what you see as the objective is simply
`model.reactions.biomass_cho.flux_expression` (forward - reverse)

Since it's an irreversible reaction the bounds for the reverse direction are simply `0 <= model.reactions.biomass_cho.reverse_variable <= 0` and it is thus ignored by the solver.

So yes, it is 'internal' behavior of cobrapy and very much desired.

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
