### ISSUE TITLE
Allow manipulation of individual media components without reassignment of entire model.medium

### ISSUE THREAD

**Issue by gregmedlock** [opencobra/cobrapy#728]
#### Problem description
I think model.medium behaves a bit counterintuitively when trying to alter the bounds for a single reaction. Basically, the property/setter approach makes model.medium look like a dictionary that is an  attribute, which should be modifiable as described below in the code block. I propose modifying the setter to account for manipulation of individual reactions rather than requiring an entire dict to change bounds for any metabolite.

Apologies if this was discussed when medium was first implemented... I am just now getting around to actually using versions of cobrapy that have medium.

#### Code Sample

```python
from cobra.test import create_test_model
model = create_test_model('textbook')

# Current approach to changing bounds for a single media component
medium = model.medium
medium['EX_glc__D_e'] = 0
model.medium = medium

# Desired approach
model.medium['EX_glc__D_e'] = 0
```

#### Actual Output
For the desired approach, nothing happens because the medium property returns a dict that is no longer associated with model.
#### Expected Output
I expect modification of model.medium when accessing it like a dictionary as above.
#### Dependency Information
<details>

System Information
==================
OS         Darwin
OS-release 17.5.0
Python      3.6.5

Package Versions
================
cobra        0.13.0
depinfo       1.4.0
future       0.16.0
numpy        1.14.5
optlang       1.4.2
pandas       0.23.1
pip          10.0.1
ruamel.yaml 0.14.12
setuptools   39.2.0
six          1.11.0
swiglpk       1.4.4
tabulate      0.8.2
wheel        0.31.1

</details>

**Comment by pstjohn** [comment]
That would be a tricky bit of code. You'd need to make 'medium' its own class which inherits from `dict`, which would then also have a `._model` attribute to know of its parent model. Then you could override `__setitem__` in the medium class to tell it to update the model accordingly.

It's definitely possible ... but it's also possible to just set `model.reactions.EX_glc__D_e.lower_bound` directly. So I think the question is how much do we value that 'Desired approach', since it would definitely complicate the implementation.

I think it's similar to `reaction.metabolites`, in that you can't directly assign to 
`reaction.metabolites['pep_c'] = -1`

**Comment by cdiener** [comment]
Pretty much agree with both of you. Would be great to have but will be quite some work to implement. What about a function that does this like `set_import`? Could be used like:

```Python
from cobra.medium import set_import

set_import(model, "EX_glc_e", 0.5)
```

**Comment by Midnighter** [comment]
Yeah, that's much more doable. Otherwise we'd have to make medium its own class (child of `dict` maybe) and assign it to the medium attribute rather than it being a property.

**Comment by pstjohn** [comment]
on a `set_import` function, I'm just not sure that's easier than setting `reaction.lower_bound` explicitly. Seems a bit like doubling the same functionality across two different functions

**Comment by Midnighter** [comment]
> on a set_import function, I'm just not sure that's easier than setting reaction.lower_bound explicitly. Seems a bit like doubling the same functionality across two different functions

While I agree that we have multiple ways, the advantage of the medium has always been that I don't need to take care of which way the exchanges are defined (fairly easy to figure out, of course).

> we might consider making media return a frozendict if we want to emphasize that its immutable as a property.

I would not do that since it prevents the workflow originally posted by @gregmedlock. At least you are able to manipulate the medium and then re-assign it even if that seems a little cumbersome.

**Comment by gregmedlock** [comment]
Based on the implementation issues raised, I think leaving as-is is best. My only concern is that attempting to modify the dict returned by the getter as if it were an attribute doesn't raise a warning, but there doesn't seem to be a simple solution to this. Just being explicit about *not* being able to do this in the user guide should be enough.
