### ISSUE TITLE
Create symbolic GPRs or otherwise improve the GPR handling

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#739]

**Comment by synchon** [comment]
The `cobra.core.gene` module hasn't been updated in a while and this might be a good issue to start with. Any thoughts on this one? I can have a go if nobody is working on this.

**Comment by matthiaskoenig** [comment]
Yes, this needs urgent updating. My thoughts
- this currently sucks, more specifically there is a lot of manual conversion between GPR strings in the model formats and the internal GPR representation
- this is speed sensitive, i.e. a lot of the model parsing (at least for SBML) goes in processing the GPRs, because they have to be converted between trees and strings. I.e. the processing and handling cannot get (much) slower as it currently is.
- this should be future proof. A major limitation of current GPRs is that the miss the stoichiometry, i.e. how many subunits of one gene and another form the final protein. The main issue is that proteins are not actually represented, but at least the subunits should be encoded correctly (these are factors 2-3 incorrect otherwise). A new implementation should be able to account for stoichiometry. E.g. a heterodimer protein A2B2 should have the GPR (2 G_A and 2 G_B)
- this should have a unique way for serialization so that GPRs can be compared for equality.

**Comment by Midnighter** [comment]
Another aspect of this was the idea to integrate genes with `optlang.Symbol`s such that one could use sympy to directly evaluate the Boolean expressions. I think taking all of this on, though, is quite a major piece of refactoring and new work. We should plan this out in a bit more detail before writing any code.

**Comment by matthiaskoenig** [comment]
@Midnighter I agree, this is a major issue and needs some planning. 
Just listed things which I noticed with the GPRs. By no means should this all be solved at once.

**Comment by cdiener** [comment]
Sorry just saw that. @matthiaskoenig, could you comment on what you mean by 

> this should be future proof. A major limitation of current GPRs is that the miss the stoichiometry, i.e. how many subunits of one gene and another form the final protein. The main issue is that proteins are not actually represented, but at least the subunits should be encoded correctly (these are factors 2-3 incorrect otherwise). A new implementation should be able to account for stoichiometry. E.g. a heterodimer protein A2B2 should have the GPR (2 G_A and 2 G_B)

A single gene copy pretty much always yields several peptides translation even from a single mRNA. So for A2B2 you would still only need one copy of G_A and G_B which in turn can yield several copies of the peptides A and B. I think the current implementation captures this pretty well. I agree that there is a relationship between mRNA/peptide/protein and enzyme abundance but this is generally not captured by (normal) metabolic models...

**Comment by matthiaskoenig** [comment]
The subunit structure of proteins is very important for all the resource balance models and models capturing protein composition. E.g. resource balance allocation or CobraME models. These models track the costs of creating proteins from a given gene. The protein composition (quartery structure and subunits) are hereby important factors for the costs. I.e. it makes a difference in cost (ATP and precursor requirements) if you have to create 1 or 2 or 4 subunits to create a functional protein. For most proteins the information of the factors is readily available. This affects also results of overexpression and downregulation, because the same downregulation affects reactions disproportionally depending on the factors in the gene - protein mapping.
E.g. if you downregulate a gene by 50% then proteins which require 1 subunit should be downregulated ~50%, but proteins requiring 4 subunits have only 12.5% activity which will have a major impact on flux distributions.

Yes, indeed many mRNAs are created from a single gene, but still different numbers of mRNA are needed to create a functional protein. 

It would be nice it this information about the subunits could be easily stored as part of the GPRs. But at the moment this is nothing which is required. I just wanted to raise awareness of the issue that such extensions will most likely be required at some point.

**Comment by cdiener** [comment]
Okay, I agree that it definitely is important for resource balance models. Though that would probably be implemented in a dedicated package like done in cobraME already (even though that looks abandoned).

**Comment by akaviaLab** [comment]
See #1158
