### ISSUE TITLE
are cobra remove_from_model() method equal to single_gene_deletion 

### ISSUE THREAD

**Issue by wh960823** [opencobra/cobrapy#749]
We want to extract particular reaction flux when manipulate single gene deletion of each gene in model. But single_gene_deletion method only return a tuple with flux of goal function. 
so we want to use remove_from_model() method to instead. We wanna to make sure whether the fluxs using this method is same as the fluxes using single_gene_deletion.

thanks.
William

**Comment by Midnighter** [comment]
Hi William,

The short answer is that no, `single_gene_deletion` and `remove_from_model` actually work differently. They should give you the same answer if used correctly but `single_gene_deletion` uses the `cobra.Gene.knock_out` method (essentially affected reactions are constrained to have zero flux, whereas `remove_from_model` actually deletes elements from the model. As I said, the resulting (non-zero) fluxes should be the same.

If you have a large model and are studying all single knock-outs, I do not recommend using `remove_from_model` because modifying the model every time will be much slower. I'm afraid that we don't have a built-in easy way to access the flux distributions of a single knock-out study but I recently wrote some code to do exactly that if you're interested.

**Comment by wh960823** [comment]
Thanks for your kind help! 

I am very instereted of getting the exact flux distributions of a single KO study which can be a great assistant of our research. Could you notice us when the code is written

**Comment by wh960823** [comment]
@Midnighter Thanks for your help. I am now used

**Comment by wh960823** [comment]
@Midnighter 
I am now using "model.reactions[i].upper_bound = 0 model.reactions[i].lower_bound = 0" way to set the reaction bounds and simulate reaction knock out. Is this way get the correct solution?

**Comment by Midnighter** [comment]
There is also the `knock_out` method which does the same and is probably a bit easier.

```python
model.reactions[i].knock_out()
```

**Comment by wh960823** [comment]
@Midnighter 

As you said, you have written some codes to access the flux distributions of a single knock-out study. We are quite grateful if you can share this codes with us.

**Comment by wh960823** [comment]
Hello, we know some about sqlite database. Could you share this removed part codes with us ? We just wanna see its implementation.

**Comment by pstjohn** [comment]
How many reactions are in your model? You could start by trying something as basic as 

```python
solutions = {}
for rxn in model.reactions:
    rxn.knock_out()
    sol = model.optimize()
    if sol.status is not 'infeasible':
        solutions[rxn.id] = sol.fluxes
    else:
        solutions[rxn.id] = np.nan

# Optional, but probably useful
solution_df = pd.Dataframe(solutions)
```

**Comment by Midnighter** [comment]
Hi @wh960823,

My apologies for the delay. My code was mixed up with some more complicated SQLAlchemy models so I didn't want to post that here. [Please check out my gist that contains the cleaned up code.](https://gist.github.com/Midnighter/7a50faa976d34cfbd59397c3152bc97e) You can simply `pipenv install` after downloading all the files into a directory and having a virtual environment with `pipenv` installed. That will give you the exact same versions of packages that I used.

Let me know about your questions. The code is a little ugly but multiprocessing is not that easy to set up efficiently.

**Comment by Midnighter** [comment]
Please let me know your questions about the code. I will close the the issue for now but feel free to re-open it.
