### ISSUE TITLE
re-pickle the pickled test models upon running tests

### ISSUE THREAD

**Issue by gregmedlock** [opencobra/cobrapy#750]
#### Problem description

There are a number of tests that load the pickled salmonella model which will fail whenever a new attribute is added to `Model`. This is causing many tests to fail as I work on #543 because several functions/methods need to be modified to account for the new groups attribute in `Model`, and the pickled model does not contain these attributes. I suggest reading the SBML file for the model and pickling it as tests are run, rather than storing a pickled model in the repository. Alternatively, it's unclear whether pickling is actually a desired functionality anymore so the pickled models could just be removed.

#### Code Sample

N/A

#### Dependency Information

N/A

**Comment by Midnighter** [comment]
I see three points that you're describing/suggesting:

1. It's painful to have so many errors when adding a new attribute to a class and loading an old pickle file.
2. Generate the pickle files on the fly.
3. Stop supporting pickle as a format altogether.

My thoughts on these points are:

1. Assuming that the outcome of a discussion on 3. is positive, I actually consider these errors a good thing. It highlights that something critical about the class has changed and that every existing pickle file out there will be broken.

   Your pain as a developer is easily remedied. Simply run `cobra/test/data/update_pickles.py` with the new class definition and you're good to go. However, that still leaves any existing models stored in pickle format in a broken state or alternatively, only legible by an older cobra version without any option to upgrade the existing model.

2. I would not like to generate them on the fly at all. That would completely subvert the purpose of the tests  in my opinion. Since it's also so easy to upgrade them, I'm very much in favor of keeping that a conscious decision.

3. I'm happy to have a discussion on our level of support for the pickle format. We need to test the pickling and unpickling operation because this is what happens in multiprocessing to transfer data. We have not really taken care in the past to warn users that their existing pickles will be broken. We kind of expect pickles to be a temporary format that can be re-generated easily when necessary. We can make this point of view our explicit policy or if there is huge demand we can improve our support of the pickle format. I have no real insight in how widely spread the use of pickle is so maybe we should poll the community?

**Comment by Midnighter** [comment]
Any other opinions on this? Otherwise I guess we'll maintain the status quo and I'll close this issue.

**Comment by Midnighter** [comment]
So I also agree that we should maintain pickles. Would you argue for better pickle support, though, or is what we currently do fine?

**Comment by pstjohn** [comment]
Another consideration I'll point out is that we use the pickled models to ensure a consistent solution for testing the summary methods. Otherwise it's hard to guarantee you'll get the same result, and the expected output will change.

**Comment by gregmedlock** [comment]
Closing sounds good to me--thanks for the informative response @Midnighter, I had no idea serialization for multiprocessing was handled with pickle. Seems all we need to do is update contribution instructions with a note about update_pickles. Maybe this should just be part of a general update of contribution instructions for v1.0?
