### ISSUE TITLE
Add functions for feasbility objectives and lexicographic constraints

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#763]
Related to #452, i think the functions @synchon started for the dFBA implementation would be useful in cobrapy. Specifically, what would people think about adding some version of

```python
def add_lp_feasibility(model):
    
    obj_vars = []
    prob = model.problem
    for met in model.metabolites:
        s_plus = prob.Variable("s_plus_" + met.id, lb=0)
        s_minus = prob.Variable("s_minus_" + met.id, lb=0)

        model.add_cons_vars([s_plus, s_minus])
        model.constraints[met.id].set_linear_coefficients({s_plus: 1.0, s_minus: -1.0})
        obj_vars.append(s_plus)
        obj_vars.append(s_minus)

    model.objective = prob.Objective(Zero, sloppy=True, direction="min")
    model.objective.set_linear_coefficients({v: 1.0 for v in obj_vars})


def add_lexicographic_constraints(model, objective_list, objective_direction):
    
    for rxn_id, obj_dir in zip(objective_list, objective_direction):
        model.objective = model.reactions.get_by_id(rxn_id)
        model.objective_direction = obj_dir
        cobra.util.fix_objective_as_constraint(model)
```

to cobra.util.solver? I might also edit cobra.util.fix_objective_as_constraint to return the objective / constraint value to avoid having to re-run a solution in a dFBA implementation.

On dFBA specifically, I'm not sure what the plans are for [synchon/dynamic-fba](https://github.com/synchon/dynamic-fba), but I think with the above functions integrated into cobrapy, dFBA would be relatively easy to implement in a single jupyter notebook in the cobrapy docs

**Comment by davidtourigny** [comment]
Hi Peter. I have just started looking into working with cobrapy (and following this thread) as part of new research project with a view to do exactly that (i.e. implement a version of dFBA). However, I am relatively inexperienced with python and much more familiar with C++, which I use write integration platforms for ODE models incorporating various plugins. My first naive attempt at dFBA with cobrapy in python suffers from the same problems you mentioned previously (speed, infeasibility of the LP), and so I started to look into a possible DFBAlab-hybrid, but lack the cobrapy knowledge to progress very quickly. I would therefore be very keen for something like you propose and to remain included in the discussion/process of development- if not to contribute very much, more so just to learn! Thanks, David

**Comment by synchon** [comment]
For the dFBA implementation, we were limited by the choice of solvers and also the choice of kinetics. We planned to implement a symbolic way to add constraints and also add _customized_ kinetic functions. Since, this will require a lot of extra base functions to work, we decided to make it a separate package. To get an overview, you can check this: https://medium.com/@synchon_mandal/gsoc-18-third-task-3fe31c56e27d :)

As for the utility functions being added, I think @Midnighter and @cdiener will have better rationale.

**Comment by Midnighter** [comment]
Welcome @davidtourigny, glad to have you come on board and I'd be happy to keep you in the loop or even have you join/take over development of the dFBA implementation. Would it be best to have a video call to get you caught up on the status quo? I'd like to prevent the work from fragmenting too much and development happening in one place if possible.

@pstjohn I think it's a good idea to add those functions. I'm not super happy about `cobra.util.solver` because it's in a weird in-between state. We mostly use it for internal functions but there are already some very useful bits of code in there. It would be nice to have one module with useful functions to export to the main cobra namespace and clearly document it as being intended for users.

**Comment by davidtourigny** [comment]
@Midnighter That would be great! My private email is davidttourigny@gmail.com if you would like to coordinate a suitable time to video chat.

**Comment by pstjohn** [comment]
On `cobra.util.solver`, agreed that its not the most intuitive place for those functions to live. But I think grouping them with things like `fix_objective_as_constraint` makes sense, which was why that seemed like the best choice.

Take a look at the implementation in #764, I'm certainly happy to move those functions to a different module if that would be better

**Comment by pstjohn** [comment]
Also, I'd be happy to join a dFBA video chat as well.
It's definitely a tough problem, since if speed is a concern you really want to avoid having to come back to python in the right-hand side function evaluation. I tried a cython version a while back, but it was cumbersome to pass custom kinetics from python (https://github.com/pstjohn/dFBA). Maybe if you used something like symengine to define the kinetic function? But you're still left re-implementing all the linear solve machinery in C, unless there was a way to pass the solver configurations from optlang at a low level to the simulator.

**Comment by davidtourigny** [comment]
@pstjohn and @Midnighter I have sent you an email regarding video chat arrangements
