### ISSUE TITLE
cobra.topology nowhere to be found

### ISSUE THREAD

**Issue by fboren** [opencobra/cobrapy#779]
#### What is up with the cobra.topology package?

I'm looking to do reporter metabolite analysis on a cobra.model I created. On the "readthedocs" page for cobrapy a package named "cobra.topology" is mentioned (see link: https://cobrapy.readthedocs.io/en/0.10.1/cobra.topology.html#cobra-topology-reporter-metabolites-module) but this package doesn't seem to exist when using cobrapy. 

Does it exist at all, if so, where can I find it/import it? If not, what are my options for doing reporter metabolite analysis?

**Comment by Midnighter** [comment]
Hi @fboren, we have indeed removed the `topology` module as it was deprecated for a while and didn't see any use. You now have a couple of options:

1. You can install an older version of cobrapy (`pip install "cobra==0.10.1"`) and see if the functionality therein suits your needs. Just a fair warning that it was not maintained very well which is why we removed it.
2. @pstjohn does one of your packages have code to transform a model into a bipartite network? I think there is room for a dedicated metabolic network package.
3. You can quickly create a graph yourself using networkx (`pip install networkx`).

```python
import networkx as nx
from cobra.test import create_test_model
from six import iteritems

model = create_test_model("textbook")
network = nx.DiGraph()
for reaction in model.reactions:
    for metabolite, coefficient in iteritems(reaction.metabolites):
        if coefficient < 0:
            network.add_edge(metabolite, reaction, coefficient=coefficient)
        else:
            network.add_edge(reaction, metabolite, coefficient=coefficient)

print(network.order())
print(network.size())
```

**Comment by Midnighter** [comment]
I'm closing this for now. Feel free to re-open if this is still an issue for you.
