### ISSUE TITLE
Setting initial conditions to optimizer to start searching from that point

### ISSUE THREAD

**Issue by sumanasri** [opencobra/cobrapy#797]
#### Problem description
Hi, Is there a way I can tell the optimizer in cobrapy to start from a set of flux values that determine the initial conditions? These are not constraints. These are initial conditions. Suppose I want to use a certain objective first and obtain a solution and then from that solution as a starting point, try out another objective, how would I do that?

Please explain:
I need to run an objective first with a set of constraints and then use the solution as an initial condition for maximization of another objective.
I have not tried anything out yet since I do not know how to do this.

Thanks for any help.

**Comment by cdiener** [comment]
Sorry for the delayed response. Even though there is no explicit way in cobrapy to do that since that depends a lot on the particular solver you use, this should actually happen most of the time automatically. All solver in cobrapy are set up to recycle as much from a previous solution as possible. In general there are 2 things that are recycled: a feasible start solution (what you are asking) and the basis for the simplex method. So if your previous solutions is still valid that means the algorithm will use it as a first guess and go from there. 

*However*, if your goal is to find the closest solution that maximizes the second objective but is the closest to the optimal solution found in your first optimization the strategy described above might not work since the optimizer will no necessarily take the shortest path to the new optimum (especially simplex methods will not). So here you would probably want something like a MOMA strategy where you obtain your first objective and then look for the closest solution that optimizes your second objective. You can use the existing MOMA API to do that for you. Here is a quick example where you want to find the flux distribution that maximized Acetate production but at the same time is closest to the maximum Biomass reference solution:

```Python3
from cobra.test import create_test_model
from cobra.flux_analysis import add_moma
import numpy as np

mod = create_test_model("textbook") 
sol_biomass = mod.optimize()
mod.objective = mod.reactions.EX_ac_e  # maximize acetate
sol_acetate = mod.optimize()

with mod:
    # add a new constraint that forces maximum acetate production
    objective_constraint = mod.problem.Constraint(mod.objective.expression, lb=sol_acetate.objective_value)
    mod.add_cons_vars([objective_constraint])
    # add minimization of absolute distance to reference solution
    add_moma(mod, solution=sol_biomass)
    sol_close = mod.optimize()

# check if still optimal
print(np.allclose(sol_close.fluxes.EX_ac_e, sol_acetate.fluxes.EX_ac_e))

# check which is closer to the reference
print((sol_biomass.fluxes - sol_acetate.fluxes).abs().sum())
print((sol_biomass.fluxes - sol_close.fluxes).abs().sum())
```

which returns:

```
True
430.0200953491616
346.1292476081368
```

So the MOMA strategy gives an optimal solution that is quite a bit closer to the reference state. If you would use quadratic MOMA this would even be guaranteed to be a unique solution.

**Comment by cdiener** [comment]
Closing for now. Feel free to reopen if it does not answer your question.
