### ISSUE TITLE
CHRR vs ACHR in cobratoolbox

### ISSUE THREAD

**Issue by kspkritika** [opencobra/cobrapy#802]
I am trying to use the sampling algorithm on cobratoolbox in MATLAB to get unbiased flux samples for EColi core model. However when I use the CHRR algorithm, the flux values for reactions corresponding to glucose uptake and biomass produced are very small (order of magnitude ~=10^-14). This does not make any sense physiologically. And when I use the ACHR algorithm, some reactions are eliminated in the final flux samples. Which defies the purpose of the problem I want to solve. I am new to cobratoolbox. Can someone guide me with a way to deal with this problem.

**Comment by cdiener** [comment]
Hi @kspkritika, this is the repository for cobrapy which is the Python implementation of the cobra methods. For questions concerning the Matlab cobratoolbox you will have better chances on their repository. See https://github.com/opencobra/cobratoolbox#tutorials-documentation-and-support.

To give some general pointers. It is quite normal that the sampled flux for the biomass reaction is much smaller than the actual maximum since you sample uniformly in all fluxes and only a few combinations yield high biomass. However, using cobrapy I do not get fluxes that small:

```Python3
In [1]: from cobra.test import create_test_model

In [2]: from cobra.flux_analysis import sample

In [3]: mod = create_test_model("textbook")  # E coli core model

In [4]: fluxes = sample(mod, 1000)

In [5]: fluxes.Biomass_Ecoli_core.decribe()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d421284c5126> in <module>
----> 1 fluxes.Biomass_Ecoli_core.decribe()

~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5065             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5066                 return self[name]
-> 5067             return object.__getattribute__(self, name)
   5068
   5069     def __setattr__(self, name, value):

AttributeError: 'Series' object has no attribute 'decribe'

In [6]: fluxes.Biomass_Ecoli_core.describe()
Out[6]:
count    1000.000000
mean        0.038286
std         0.035073
min         0.000022
25%         0.011736
50%         0.027670
75%         0.055456
max         0.238575
Name: Biomass_Ecoli_core, dtype: float64

In [7]: mod.optimize()
Out[7]: <Solution 0.874 at 0x1049faa90>
```

Reactions being removed could be a consequence of quasi-fixed reactions, thus meaning reactions whose flux will not vary at all and is pretty much constant. Those are often removed by samplers since they trip up the algorithms. 

You might want to check if you have any contraints set on your model that disallow growth. Maybe your glucose import constraint is formulated in the wrong direction (allowing export but no import) or something similar.

You will probably receive more help with the cobratoolbox family as indicated above. 

Will close that for now but feel free to reopen if you have a question related to cobrapy.
