### ISSUE TITLE
Using model tolerance in functions which set threshold in flux results

### ISSUE THREAD

**Issue by synchon** [opencobra/cobrapy#823]
This issue is meant to decide how we handle the functions which typically use arguments like `zero_cutoff` or similar. Here is a list of them (might have missed a few):

- [x] cobra.flux_analysis.loopless.add_loopless
- [x] cobra.flux_analysis.loopless.add_fva_iter
- [x] cobra.flux_analysis.fastcc.fastcc
- [x] cobra.flux_analysis.variability.find_blocked_reactions
- [x] cobra.flux_analysis.phenotype_phase_plane.production_envelope

For now, I see two ways:

1. Set the `zero_cutoff = None` in the function definition and set it to `model.tolerance` inside the function (which would still preserve the definition), or,
2. Replace the `zero_cutoff` with `**kwargs` and let the user know in the docstring.

In any of the cases, there's always the provision for the user to specify the tolerance during function call. Do we keep this or make it only possible to access the tolerance by setting the `model.tolerance` (in which case there would no `zero_cutoff` or `**kwargs`)?

**Comment by Midnighter** [comment]
I vote for the first option that you mention.

**Comment by cdiener** [comment]
So I would even prefer if tolerances can only be set for the model and get used by the functions (meaning removing the zero cutoff parameter). For instance having having a zero cutoff smaller than the tolerance does not make sense since that would give arbitrary results (having cutoff > tolerance does though).

**Comment by synchon** [comment]
In that case, we can just issue a warning and take the `max` of `zero_cutoff` and `tolerance`.

**Comment by Midnighter** [comment]
> In that case, we can just issue a warning and take the max of zero_cutoff and tolerance.

Sounds good. I would not like to change the function signatures too much. So I prefer keeping the argument.

**Comment by taylo5jm** [comment]
I understand that changing the function signatures is undesirable, but it seems to me that removing the `zero_cutoff` argument from these functions would decrease code complexity and increase readability. As it stands now, the logic to check whether or not `zero_cutoff` > `tolerance` has to appear in every function where `zero_cutoff` is used. If that logic were moved to the `Configuration` class, it only has to be in one place.

**Comment by Midnighter** [comment]
I think we can definitely introduce a utility function to do that. I'm against removing the function argument for three reasons: (1) The default zero cutoff should be equal to the solver tolerance which is already a global default. (2) Every function should only read values from the global configuration if an argument was not passed. It should at all times be possible to override the global value. (3) I really don't see another good reason to break existing code where the `zero_cutoff` was set manually.

**Comment by taylo5jm** [comment]
I think those are reasonable rules to follow. In support of your second point, what do you think about adding `processes` as an argument to the `geometric_fba` signature? Right now, I believe `geometric_fba` will use all of the available cores, since the `processes` argument is not exposed in the `flux_variability_analysis` call and the function will end up using the value in the `Configuration` object. 

I am happy to make a PR if that change is desirable.

**Comment by Midnighter** [comment]
>  what do you think about adding processes as an argument to the geometric_fba signature?

That'd be fantastic.
