### ISSUE TITLE
Change reaction rate

### ISSUE THREAD

**Issue by wrshoemaker** [opencobra/cobrapy#848]
Hello,

I've gone through the documentation and I could not find a straightforward way to change the rate of a reaction. I'm looking to model the effects of mutation on a metabolic network and I found how to remove and reverse reactions, but not how to change the reaction rate by a small amount. Perhaps this option is in the documentation using different terminology, but I did not see it.

Best,
Will

**Comment by Midnighter** [comment]
It's not explicit enough in the docs. Just like you would modify bounds in order to reverse a reaction, you can use it to enforce a certain minimum flux or restrict the maximum possible flux, for example,

```py
model.reactions.PFK.bounds = 0.5, 5
```

enforces a minimum flux of 0.5 mmol / gDW / h through PFK in forward direction and a maximum on that.

```py
model.reactions.PFK.bounds = 0, 1
```

enforces a maximum flux of 1 mmol / gDW / h.

Hope that helps

**Comment by wrshoemaker** [comment]
That's very helpful. Thank you for the clarification.
