### ISSUE TITLE
Equal reaction bounds lead to AssertionError

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#862]
Another similar use-case to consider here: [this model was just published](https://www.frontiersin.org/articles/10.3389/fmicb.2019.01283/full) online today. There are 3 reactions for which `model.lb == model.ub` -- meaning that cobrapy yields the error `AssertionError: lower bound is greater than upper` when I try to load it in.

Because I can't load this SBML model into cobrapy at all, I am forced to load into MATLAB to fix these issues, then I can load into cobrapy and use the model. 

Would be nice if some of these types of things just returned a warning instead of an error, because otherwise invalid models just aren't compatible with cobrapy.

_Originally posted by @jtyurkovich in https://github.com/opencobra/cobrapy/issues/789#issuecomment-505485728_

**Comment by Midnighter** [comment]
I cannot reproduce this with the latest cobra version. Equal bounds are possible and should be possible.

```py
from cobra.test import create_test_model

m.reactions.PFK.bounds = 10, 10
```

**Comment by Midnighter** [comment]
I just loaded the model that you linked as well. I get a few warnings but no errors. Please try again after upgrading cobra.

@matthiaskoenig one warning I get is:
```
SBML package 'l3v2extendedmath' not supported by cobrapy,information is not parsed
```
is that something we should support? I haven't looked specifically at what they use it for.

**Comment by matthiaskoenig** [comment]
@Midnighter The warning can be safely ignored. 

What happens in the parser is that it looks for all additional packages which are registered in the model. The warning just list the packages cobrapy does not use any infomation from. It is just to inform the user that there is additional information in the model, but cobrapy is not making any use of it at the moment. 
Examples are for instance `layout` information. SBML L3V2 automatically registers a package which allows to extend math (even if it is not used in the model), consequently this warning was issued for all L3V2 models (which this is the first L3V3 model I see in the wild besides my own models).
I removed the unnecessary warning. 
There is no math in normal fbc models (and also not in this model).

FBC problems at the current state do not need any math, as soon as we want to go towards dynamical fbc models, or parameter bounds defined via math expressions (which is completely supported by SBML right now and a very nice construct), we have to start taking care of math.
To give an example:
In SBML it is possible to define bounds like
```
p_ub1 = 2* p_ub2
p_ub3 = min(p_ub1, p_ub2)
```
I.e. the bounds are not hard coded as numerical values but as math expressions which would translate into additional constraints.
Off topic now. In summary: warning can be ignored and is fixed in the `sbml-bugfix` pull request.

Just a general announcement because I saw it again in the model:
- please move to `https` identifier.org annotations instead of using `http`, i.e. use `https://identifiers.org/ec-code/2.A.26.1.#" instead of `http://identifiers.org/ec-code/2.A.26.1.#" if you are annotation models.

**Comment by jtyurkovich** [comment]
Apologies -- you're right, I was using a slightly older version of cobrapy. I should've checked that before posting on here (my fault). 

I also cannot replicate my original error after upgrading cobrapy to the latest version.

Thanks for the help!

**Comment by Midnighter** [comment]
Glad it's sorted out :slightly_smiling_face:
