### ISSUE TITLE
Installation failures

### ISSUE THREAD

**Issue by beacamara** [opencobra/cobrapy#910]
Hello,
I am trying to install cobrapy following the instruction, but still 5 failures related to solvers came up, especifically  the failures are related to gurobi solver. The solvers I have installed are gurobi, glpk, cplex following corresponding instructions. 

When using optlang module directly in python terminal the solvers_interface seem to work perfectly.

optlang.available_solvers                                              
Out[14]: {'GUROBI': True, 'GLPK': True, 'MOSEK': False, 'CPLEX': True, 'SCIPY': True}

In addition to this, all summary_methods fail and they do not print any result as they should be.

[cobra_test_result.txt](https://github.com/opencobra/cobrapy/files/3685277/cobra_test_result.txt)

Please, could you take a look to the attached file showing the results of  test_all()?

Thank you in advance

Beatriz Cámara

**Comment by Midnighter** [comment]
Hi Beatriz,

Sorry for not responding to your other troubles earlier. These issues are always hard to sort out remotely. I think what is going on is the following: All failures come from tests with the Gurobi solver. Even where this is not explicitly mentioned, cobrapy uses Gurobi as the preferred solver when it is available in your environment. Unfortunately, due to how the Gurobi license activation works, we cannot test Gurobi on Travis CI. That's why you are catching all these failures and we have not before.

Then there is one other test that likely fails because we recently changed the way that summaries work.
`cobra/test/test_core/test_summary/test_metabolite_summary.py::test_metabolite_summary_to_frame_with_fva[optlang-glpk-0.99-fdp_c] FAILED`

I'm afraid that it will take some time to dig into this. My suggestion is that you use CPLEX for now for your work (also Gurobi should be fine for most tasks).

**Comment by beacamara** [comment]
Dear Midnighter,

Thank you so much for your answer. This explains all the failures that I have already obtained with the test_all() function.

I will do what you have already recommended me to use CPLEX for now. But if I have understood correctly at present all summary methods will not print any result, independently of the solver used, won't it?

Thank you again

Beatriz
