### ISSUE TITLE
different FVA results for copied model

### ISSUE THREAD

**Issue by zeawoas** [opencobra/cobrapy#924]
### Context / problem description:
I want to remove reactions never carrying any flux from the model. To achieve this I run FVAs and ditch all the reactions whose sum of absolute min and max values is below a certain threshold. Doing this I noticed that some models were unable to grow after the manipulation. The reason seems to be that FVA on CPLEX* returns different results for the original models vs copies with differences exceeding numerical precision by far. Since I'm a rather casual cobrapy/optlang user I don't feel competent to find the root cause on my own, hence the issue. 

*I say CPLEX because with `m.solver = 'glpk'` the problem goes away. However, the same is true after switching back to CPLEX. So it might just be due to the process of switching interfaces and not GLPK itself. 

#### Code Sample

```python

import cobra
import cobra.test
from cobra.flux_analysis import flux_variability_analysis as FVA


m = cobra.test.create_test_model('ecoli')
m2 = m.copy()

fva = FVA(m)
fva_repeated = FVA(m)           #repeat FVA to show order of magnitude of expected differences
fva_m2 = FVA(m2)

diff_repeated = fva.abs().sum(1) - fva_repeated.abs().sum(1)
diff_m2 = fva.abs().sum(1) - fva_m2.abs().sum(1)

print(f'diff for repeated FVA:\nmax={diff_repeated.abs().max()}\nsum: {diff_repeated.abs().sum()}\n')
print(f'diff for FVA with m2:\nmax={diff_m2.abs().max()}\nsum: {diff_m2.abs().sum()}')

```

#### Actual Output

diff for repeated FVA:
max=3.667537384899333e-10
sum: 2.4761421557108532e-09

diff for FVA with m2:
max=0.0010747147607216767
sum: 0.0013212928630325297

#### Expected Output

Differences at numerical-precision-level also between the FVAs of the original and copied models. 

#### Dependency Information
<details>

System Information
==================
OS                              Linux
OS-release 4.14.9-1.el7.elrepo.x86_64
Python                          3.6.9

Package Versions
================
cobra                       0.16.0
depinfo                      1.5.1
future                      0.17.1
numpy                       1.17.2
optlang                      1.4.4
pandas                      0.25.1
pip                         19.2.3
python-libsbml-experimental 5.18.0
ruamel.yaml                 0.16.5
setuptools                  41.2.0
six                         1.12.0
swiglpk                     4.65.0
wheel                       0.33.6

</details>

**Comment by cdiener** [comment]
Sounds similar to a problem with gurobi we are having right now. Will investigate further but it's definitely optlang-related.

**Comment by cdiener** [comment]
Okay, had some time to look into that. First of all I think your comparison should be changed to something like `(fva - fva_m2).abs().max(1)` to be closer to an actual norm (you can use sum or mean instead of max though). However, that does not really change the conclusion here.

I can reproduce that behavior with cplex, but also GLPK and gurobi to varying extents. The problem seems to be in a few reactions that have a close to 0 upper limit in FVA with `OPHHX3` being the one showing the largest discrepancy. This reactions uses many of the small molecules which often have large stoichiometries. Ergo, I suspect those reactions to be numerically unstable. The first comparison with the repeated FVA is a bit flawed, because here the solver will recycle the previous solution basis which makes it more likely to get the same result. If you use `create_test_model('ecoli')` twice and run FVA you get similar results to your second comparison (some small discrepancy). 

In the end I do think this is due to numerical instability in the ecoli model. Why? The discrepancy does not arise in the salmonella or textbook model. Also if you switch the solver to `glpk_exact` you will see a lot of infeasibility errors. This arises to the initial biomass constraint that is set on FVA. Since this has some random error within the solver tolerance this can propagate into larger variations within the individual FVA iterations. You can see that effect yourself by varying the `fraction_of_optimum` parameter in the `FVA` function to (1.0 - 1e-6 and 1.0 - 1e-4). Here, each of those will shrink the discrepancy approximately by a factor of 100. 

Also important to note that the tolerances are only controlled on the level of optimality (how close are you to the optimum) and feasibility (how well do you comply with the constraints). There is generally no control for tolerances on individual primal values (ergo fluxes). Also the tolerances usually act on the preconditioned model which is not necessarily the same as the original model. In summary: it is really hard to control the accuracy of individual fluxes. I don't think that we can solve this here. We could automatically lower the `fraction_of_optimum` by some tolerance to avoid this but I'd rather have the user do that explicitly...

**Comment by Midnighter** [comment]
I wanted to add here that there also exists a convenience function for identifying blocked reactions:

https://cobrapy.readthedocs.io/en/stable/autoapi/cobra/flux_analysis/variability/index.html#cobra.flux_analysis.variability.find_blocked_reactions

It uses FVA under the hood so it will suffer from the same numerical instabilities but it does take into account the tolerance threshold to decide if a reaction is blocked.

**Comment by zeawoas** [comment]
thanks for looking into it and the pointer to `find_blocked_reactions()`. It solves my original problem, where some models were not growing after removing below-threshold reactions.

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
