### ISSUE TITLE
minimal_medium IndexError: list index out of range

### ISSUE THREAD

**Issue by PkiwiBird** [opencobra/cobrapy#928]
#### Problem description
I applied FASTCORE algorithm to a recon3D model for different samples. I got sample specific models. Then I put bounds of drains associated with import of medium components from -1000 to 1000, while putting remaining drains from 0 to 1000 in each sample model. Then tested FBA, but models were infeasible.
To find other drains that have to be opened so that models are feasible, I first opened all drains of each sample model to use the function 'minimal_medium': `minimal_medium(OpenedSampleModel, 0.1, minimize_components=True) ` For three of the samples it worked fine and when opening their minimal medium drains they were feasible. For one sample however it gave the error:
```
Traceback (most recent call last):
  File "C:\Users\Tania\.conda\envs\models\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-e34d9e64d654>", line 2, in <module>
    minMed_01 = list(minimal_medium(OpenedSampleModel, 0.1, minimize_components=True).index.values) # most cell lines have a growth rate of 0.1
  File "C:\Users\Tania\.conda\envs\models\lib\site-packages\cobra\medium\minimal_medium.py", line 222, in minimal_medium
    medium = media[0]
IndexError: list index out of range
```
Below is a pickle of `OpenedSampleModel`
Could you please tell what is wrong?
[OpenedSampleModel.zip](https://github.com/opencobra/cobrapy/files/4127685/OpenedSampleModel.zip)

**Comment by cdiener** [comment]
Thanks for providing the model I'll investigate and get back to you.

**Comment by cdiener** [comment]
Hi, looks like your model was pickled using gurobi as the solver which means I can't unpickle it on my machine. Would you mind switching the solver before pickling?

```Python
model.solver = "glpk"
```

Thanks!

**Comment by tanialbb** [comment]
> Hi, looks like your model was pickled using gurobi as the solver which means I can't unpickle it on my machine. Would you mind switching the solver before pickling?
> 
> ```python
> model.solver = "glpk"
> ```
> 
> Thanks! What I can already say that the problem is that the optimization does not converge (can't find an optimal solution)...

[OpenedSampleModel.zip](https://github.com/opencobra/cobrapy/files/4129869/OpenedSampleModel.zip)
goes

**Comment by cdiener** [comment]
Hi,

so your model optimizes fine with me with GLPK and CPLEX:

```Python
In [1]: import pickle

In [2]: from cobra.medium import minimal_medium

In [3]: with open("OpenedSampleModel", "rb") as inf:
   ...:     mod = pickle.load(inf)
   ...:

In [4]: med = minimal_medium(mod, 0.1, minimize_components=True)
the MIP version of minimal media is extremely slow for models that large :(

In [5]: med
Out[5]:
EX_pchol_hs[e]    0.008336
EX_pglyc_hs[e]    0.001457
EX_utp[e]         1.546373
EX_HC00009[e]     0.000168
EX_M02353[e]      0.000157
EX_M01569[e]      0.002772
dtype: float64
```

However, I have to mention that if I run this code several times I occasionally see the same error as you do and it's basically an inconsistent result where the optimizer can't find an optimum again that it found before. This is usually a numerical problem and this sometimes happens with larger models and integer programming. Gurobi is also a bit more vulnerable to this than other solvers in my experience. You could increase you solver tolerance as described in the documentation for `minimal_medium` but this will also make it slower. Also you could just try to reload the model from the pickle and running the code again (maybe with a different solver). I will send a PR that gives a more informative warning in those unstable cases.

On a side note for most use cases `minimize_components=False` is the way to go since there is at least some biological intuition to it. Selecting a small number of components is usually only useful along with other constraints and if you want to design an actual growth medium to test in the lab for instance. Otherwise the model will just try to import a small amount of biomass components directly and break them down internally into the remaining biomass components.

**Comment by cdiener** [comment]
Might also be worthwhile to update your optlang and gurobi packages in case this hasn't happened recently.

**Comment by tanialbb** [comment]
With cplex worked fine.
Thank you
