### ISSUE TITLE
Loopless FBA objective value is zero

### ISSUE THREAD

**Issue by marvinvanaalst** [opencobra/cobrapy#935]
When I run the example from your loopless FBA documentation, I get the objective value 0 (which is also displayed in the rich output), while the flux of the biomass reaction is non-zero.

```python
import cobra.test
from cobra import Reaction, Metabolite, Model
from cobra.flux_analysis.loopless import loopless_solution

salmonella = cobra.test.create_test_model("salmonella")
nominal = salmonella.optimize()
loopless = loopless_solution(salmonella)

print(loopless.objective_value)
>>> 0.0

print(loopless.fluxes.biomass_iRR1083_metals)
>>> 0.380007972274052
```

Do I misunderstand anything about the loopless concept, or is this just bug?

<details>
System Information
==================
OS                     Linux
OS-release 4.15.0-76-generic
Python                 3.6.7

Package Versions
================
cobra                       0.17.1
depinfo                      1.5.1
future                      0.18.2
numpy                       1.18.1
optlang                      1.4.4
pandas                       1.0.1
pip                         20.0.2
python-libsbml-experimental 5.18.0
ruamel.yaml                 0.16.5
setuptools                  41.2.0
six                         1.14.0
swiglpk                     4.65.0
wheel                       0.33.6
</details>

**Comment by Midnighter** [comment]
The objective value is not always the same as the biomass flux. As a simpler example, when you use parsimonious FBA, the objective is to minimize the sum of active fluxes while maintaining a certain biomass flux. Also in that case the objective value will be very different from the biomass flux. So it's not a bug.

**Comment by cdiener** [comment]
This is true in general but not for `loopless_solution` where it is set to be the old objective expression https://github.com/opencobra/cobrapy/blob/06f86dcc11f39200a8293d501334417c17b5b477/cobra/flux_analysis/loopless.py#L179. So it does look like a bug. I can reproduce the problem and it is due to the constraint that I set for `loopless_objective` which is essentially free and creates some problems for larger models. Would be a simple fix here of choosing more appropriate bounds or adding a helper variable.
