### ISSUE TITLE
Metabolite ID conversion

### ISSUE THREAD

**Issue by greenetarget** [opencobra/cobrapy#952]
I've downloaded a model (in xml) made by others, metabolites are in SEED ID (eg. dATP is id="M_cpd00115_c0" name="dATP[c0]"),  

Is there a way I can convert these IDs into "datp_c" style that is commonly used in many E coli models? from which database?

(I'm very new to this, any help will be much appreciated! thank you!)

**Comment by Midnighter** [comment]
Hi there,

The kind of identifier that you are looking for comes from [BiGG](http://bigg.ucsd.edu/). It is certainly possible to map SEED identifiers to BiGG ones but it may require a substantial amount of manual work since the identifiers do not always map 1:1.

A good starting point for attempting such a mapping is [MetaNetX](https://www.metanetx.org/).
